### ISSUE TITLE
Document WeChat notification support

### ISSUE THREAD

**Issue by juliusv** [prometheus/docs#1005]
WeChat support got added in https://github.com/prometheus/alertmanager/pull/1059, but it's not documented yet on https://prometheus.io/docs/alerting/configuration/

**Comment by infoverload** [comment]
Can I take this one?

**Comment by juliusv** [comment]
@infoverload Sure!

**Comment by juliusv** [comment]
@infoverload Actually it seems this was already fixed in https://github.com/prometheus/docs/pull/977/files, but this issue didn't get autoclosed, maybe because the actual commits in that PR didn't contain a "Fixes: ..." notice?

**Comment by juliusv** [comment]
Oh. Because it hasn't been merged yet.
