### ISSUE TITLE
Add custom collectors / collectors support

### ISSUE THREAD

**Issue by lutangar** [prometheus/docs#1077]
Hi there,

I thought it would be interesting to discuss this matter here.

I created the following exporter with this Prometheus client:
https://github.com/LePetitBloc/bitcoind-exporter

But I stumble upon an issue, related to **direct instrumentation**, while discussing my submission with @brian-brazil :
> This is where you need to use const metrics rather than direct instrumentation. I don't think the node.js client quite supports that, so you'd have to rewrite in Go/Java/Python.
> https://github.com/prometheus/docs/pull/1011#issuecomment-386616057

As per @brian-brazil this client doesn't seem to support custom collectors. It was also mentioned in #177.

I might be mistaken by linking direct instrumentation problems to the missing collectors feature, but from what I get it is related.
I'd like to help on the matter but I don't fully grasp the problem nor the solution.

Maybe we could come up with something together?

Cheers.
> **Resources**
> The relevant Prometheus doc on collectors can be found here:
> https://prometheus.io/docs/instrumenting/writing_exporters/#collectors
>
> And here is the custom collector reference implementation in Python:
> https://github.com/prometheus/client_python#custom-collectors

**Comment by lutangar** [comment]
Woops wrong repo.

**Comment by RichiH** [comment]
Better to take this to the dev mailing list @ https://groups.google.com/forum/#!forum/prometheus-developers than to an issue; that would have wider coverage. See you over there :)

**Comment by lutangar** [comment]
Hey @RichiH, thanks, but this issue was meant for a Prometheus javascript client:
https://github.com/siimon/prom-client
I might bring this issue over there to get some help though.
Cheers.
