### ISSUE TITLE
PushGateway class link not working in docs and pushing.md

### ISSUE THREAD

**Issue by IMS94** [prometheus/docs#1080]
The link to PushGateway class in [docs](https://prometheus.io/docs/instrumenting/pushing/) and [pushing.md](https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/pushing.md) are not working. I could have fixed that, but don't know where the new class docs are at.

**Comment by brian-brazil** [comment]
Hmm, @grobie https://prometheus.io/client_java/ is no longer showing the javadoc from the client_golang repo which are in the gh-pages branch.

**Comment by lucperkins** [comment]
@brian-brazil @grobie I'm seeing the Javadoc at http://prometheus.github.io/client_java/. Was it previously also hosted under https://prometheus.io?

**Comment by brian-brazil** [comment]
I can tell you that that link used to work, but I haven't tried using it in while.

**Comment by lucperkins** [comment]
Hmmm. Well, I'm not seeing anything in the docs repo related to Javadoc generation, so I'd say it's safe to consider the prometheus.github.io/client_java the canonical home for that.

**Comment by brian-brazil** [comment]
It was a github thing, it never went through the docs repo.
