### ISSUE TITLE
Link to PushGateway java class in documentation is missing/broken.

### ISSUE THREAD

**Issue by DrewMcArthur** [prometheus/docs#1087]
On the [Instrumenting/Pushing Metrics page](https://prometheus.io/docs/instrumenting/pushing/), there is a link to the [PushGateway Java Class](https://prometheus.github.io/client_java/io/prometheus/client/exporter/PushGateway.html), which does not lead anywhere.

**Comment by lucperkins** [comment]
This issue has been fixed in #1085. Thanks for reporting!

**Comment by DrewMcArthur** [comment]
oh thanks! sorry I just realized my search was only for open issues, my bad.
