### ISSUE TITLE
Broken link exposition_format page 

### ISSUE THREAD

**Issue by sbilello** [prometheus/docs#1107]
https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md
If you click on  "There's a variety of `client libraries`" that link is broken.

**Comment by brian-brazil** [comment]
This works as expected on https://prometheus.io/docs/instrumenting/exposition_formats/, which is where this is officially served.

**Comment by sbilello** [comment]
This link is broken: https://github.com/prometheus/docs/blob/master/docs/instrumenting/clientlibs
