### ISSUE TITLE
Where can I find docs for prometheus labels

### ISSUE THREAD

**Issue by sta-szek** [prometheus/docs#1109]
Hi,
I don't know how but I found that we can use labels in prometheus scrape jobs instead of "hardcoding" values. E.g. we can use
```
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_username]
          action: replace
          target_label: __basic_auth_username__
          regex: (.+)
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_password]
          action: replace
          target_label: __basic_auth_password__
          regex: (.+)
```
which was found here: https://github.com/mrsiano/openshift-grafana/blob/master/prometheus-high-performance.yaml#L290-L297

Is there any docs describing what annotations are allowed and what are they for?

I want to use static_config annotations so I can have only one job in prometheus and then configure static configs from k8s Pod labels.

**Comment by simonpasquier** [comment]
The list of labels that can supplement the scrape configuration is here: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config

Be aware that what the snippet you've pasted won't do what you expect it to do: discovered labels can't be used to override the Basic-Auth username and password defined in the scrape configuration (see #4026 for instance).

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
