### ISSUE TITLE
Provide examples of valid names of all four metric types

### ISSUE THREAD

**Issue by jhdedrick** [prometheus/docs#1132]
Disclaimer: I'm a Prometheus noob, specifying a prometheus schema for a fairly complex system for the first time.  

I have to say the entire Best Practices section is unexpected and fantastically useful - it's making it much easier for someone in my position to get off on the right foot.  In particular the "Metric and Label Naming" page is helpful; but would be even more so if there were a few complete examples of all four metric types.  I know naming is mostly arbitrary, but there are a few required elements (e.g. "bucket{..}" has to come last).  It would be great to spell those out explicitly, and show some complete results.

Overall, great work!
-J

**Comment by lucperkins** [comment]
@jhdedrick Is there a particular place in the documentation that you'd find this most useful?

**Comment by brian-brazil** [comment]
That section is complete, the only convention you need to be aware of is _total on counters. Things like _bucket are an implementation detail that's taken care of for you by client libraries.

**Comment by jhdedrick** [comment]
Brian: I've read the docs fairly thoroughly, and I'm familiar with all the metric types. My task is to _specify_ a set of metrics to be implemented by someone else; they will follow whatever convention I define, so I want to name things in a clear, extensible way. 

It seems from your comment that the bucket boundary is not part of the metric name, but rather a parameter to the library function that creates it.  It would be helpful to state that somewhere; it's not in the documentation, nor e.g. in the Python library (there's an example of creating a histogram, but no reference info on the available parameters/syntax - e.g. it doesn't tell you how to specify the buckets.)

Luc: I'm not sure of the best place.  It could go in the "instrumenting" section - a language-independent overview of the general signature of the metric creation functions, or in the best-practice/Metric and Label Naming section.

**Comment by brian-brazil** [comment]
> It seems from your comment that the bucket boundary is not part of the metric name, but rather a parameter to the library function that creates it.

It depends on what level you're talking about. To Prometheus it's a label. To the exposition format it's a label with a specific convention as part of a metric family. To a client library it's a parameter to a Histogram.

> in the Python library (there's an example of creating a histogram, but no reference info on the available parameters/syntax - e.g. it doesn't tell you how to specify the buckets.)

https://github.com/prometheus/client_python#histogram

> It could go in the "instrumenting" section - a language-independent overview of the general signature of the metric creation functions

I'm not clear what it is you're looking for. As far as I can see we already have all of this documented.

**Comment by jhdedrick** [comment]
Perhaps you're right - this may be just the normal amount of groping around
for a person new to both this tool and the genre. I'd be fine with closing
this item.
