### ISSUE TITLE
Write blog post on LTS offerings based on PromCon 2018 panel

### ISSUE THREAD

**Issue by mhausenblas** [prometheus/docs#1163]
As suggested during PromCon, I'd volunteer to write a blog post on LTS offerings. Just an overview, with one paragraph per offering and the video of the panel embedded.

**Comment by mhausenblas** [comment]
FYI and in case you have input or suggestions @juliusv @fabxc @tomwilkie @pauldix @nikunjgit

CC: @brancz and thanks for the guidance

**Comment by brancz** [comment]
I think a blog post on giving an overview of LTS solutions would be great, as it's the most asked for whenever we do open questions about Prometheus.

**Comment by brancz** [comment]
We're not intending to solve long-term-storage as the prometheus project, this blog post would be an overview of available solutions, similar to how they were discussed in the panel.

**Comment by RichiH** [comment]
Agreed; on the other hand, we could put it there as not on the
roadmap, but foreseeably solved with these other mechanisms.

**Comment by mhausenblas** [comment]
Thanks for the feedback so far. First [minimal draft is up](https://github.com/mhausenblas/docs/blob/c4c33a757e62813519a5a302f99313a78864341a/content/blog/2018-09-03-lts-options.md), please let me know if I'm missing something.

**Comment by RichiH** [comment]
The skeleton is logical, the actual content is the part which would need review.

I still maintain that this should be part of our docs, though. If not roadmap then maybe https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage ?

**Comment by brian-brazil** [comment]
This should not be part of our docs, it's not our place to maintain documentation on 300+ integrations and their design decisions - rather I think we should like to them and let them describe themselves.

**Comment by mhausenblas** [comment]
> The skeleton is logical, the actual content is the part which would need review.

@RichiH thanks for the feedback and yes, surely it's the content that's interesting, but also, really I was interested if I'm missing one of the panelists here? ;)

> This should not be part of our docs, it's not our place to maintain documentation on 300+ integrations and their design decisions - rather I think we should link to them and let them describe themselves.

I tend to agree with @brian-brazil here, it's not scalable to keep non-core docs up-to-date. The blog post really should serve as a snapshot of what is the current state and link to the appropriate places, leaving it up to the offerings to make a point for where and when to use them.

**Comment by mhausenblas** [comment]
For now, I've embedded the livestream video (timestamped to the panel). Basic content is here now, please provide feedback if you want to see more (for example, I could add architecture diagrams to each).

**Comment by mhausenblas** [comment]
Any comments here? Also, does anyone know when the final videos are up?

**Comment by simonpasquier** [comment]
From prometheus-dev IRC:

> We're still waiting for iStream to finish their post-process

**Comment by mhausenblas** [comment]
Any updates re the post-processing?

**Comment by mhausenblas** [comment]
Still no videos @brancz?

**Comment by SuperQ** [comment]
Nothing yet, we're currently waiting for Google to approve the videos. :face_with_head_bandage:

**Comment by mhausenblas** [comment]
Seems the videos are online now?

**Comment by mhausenblas** [comment]
Can someone merge this please?

**Comment by juliusv** [comment]
@SuperQ Are the videos officially released? I see them on https://www.youtube.com/channel/UC4pLFely0-Odea4B2NL1nWA, but no announcement or links to them yet? But if this post here is linking directly to the video in question, I think it doesn't need to be blocked anymore?

**Comment by juliusv** [comment]
@mhausenblas 

> Can someone merge this please?

I don't see a pull request?

**Comment by mhausenblas** [comment]
Doh, sorry @juliusv … now?

**Comment by SuperQ** [comment]
@juliusv Yes, the videos are official. I didn't have time to `[ANN]` before heading to KubeCon. :disappointed:
