### ISSUE TITLE
Do counters reset when server changes in HA mode

### ISSUE THREAD

**Issue by devendra-nvidia** [prometheus/docs#1189]
Let's say I have three servers running in HA mode and the server is counting errors using a counter.
After leadership change, the new instance will start counting from 0. 
I am trying to understand how will the counter show up in graphs. Will the counter drop to zero?

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
