### ISSUE TITLE
How to get maximum of a sum over a period of time

### ISSUE THREAD

**Issue by mixaal** [prometheus/docs#1194]
I've a following architecture

```
| Prometheus |   ----> discovers and pulls -----> | metric exporter |    <--- REST register metric value, timestamp and a coupe of labels
```
I can't use push gateway since I can't discover Prometheus from metric exporter component, so we use pull of the metric from it.

I need to sum all the data for certain period of time. Currently I use the following query:

```
sum(my_metric) by (label1) 
```

and I use a query_range API with `start`, `end` and `step`. I've the following issue there:

 Based in the `step` value it might happen I can miss the metric => something I need to avoid. E.g. if `start=now()-1hour`, `end=now()` and `step=900` I would to get 4 values but no miss (e.g. in case the metric was reported in a different time than the step sampled)

Example:
I reported the following metrics:
```
{"metric":{"pdbID":"pdb15"},"values":[[1539607976,"2712524"],[1539608006,"2712524"] ...
```
and I want to see the maximum value even if the metrics got reported only once, however the values I see depends on the `step`:

```
curl -kv "http://localhost:9090/api/v1/query_range?query=sum%28cell_value%29%20by%20%28pdbID%29&start=1539527216&end=$NOW&step=3000"
....
{"metric":{"pdbID":"pdb15"},"values":[[1539608216,"2712524"]]}
```

When I use different step I got different results - I know this is useful for graph purposes but I don't know how to query for the max value of the sum withing certain period of time. Can you please advice?

Thanks,
Michal

**Comment by simonpasquier** [comment]
IIUC you want to do `max_over_time((sum(my_metric) by (label1))[1h])` but it isn't supported (yet, see https://github.com/prometheus/prometheus/issues/1227). You can define a recording rule for `sum(my_metric) by (label1)` and then `max_over_time(<recorded metric>[1h])`.

**Comment by mixaal** [comment]
Thanks you this works good. Is it possible to say instead of [1h] something like start=2pm and end=3pm? And still use the plain query, not query_range. Thanks.

**Comment by simonpasquier** [comment]
You can use the `time` parameter to define the evaluation timestamp, see https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
