### ISSUE TITLE
Delete series API doc does not up to date with the latest code implementation

### ISSUE THREAD

**Issue by liaoishere** [prometheus/docs#1291]
Delete series API has changed in 2.0 release, see: https://groups.google.com/forum/#!msg/prometheus-users/ToMKsb9fYp8/az6afuX3CgAJ

But the doc(https://prometheus.io/docs/prometheus/latest/querying/api/#delete-series) doesn't update. Any plan for it? If you guys need help,  I'd like trying to contribute.

**Comment by brian-brazil** [comment]
Those are the correct docs as of 2.1, v2 shouldn't be used.

**Comment by liaoishere** [comment]
Sorry I didn't try it in greater version. Thanks for help.
