### ISSUE TITLE
prometheus如何配置api_server

### ISSUE THREAD

**Issue by dingxinxinssg** [prometheus/docs#1293]
level=error ts=2019-02-22T08:49:23.964234913Z caller=main.go:218 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:289: Failed to list *v1.Pod: Get https://10.10.0.1:443/api/v1/namespaces/monitoring/pods?resourceVersion=0: x509: certificate signed by unknown authority"
prometheus 默认连接apiserver是https://10.10.0.1:443,如何把这个api_server配置成k8sMasterIP:8080的地址，我通过APIServerConfig配置不生效。

**Comment by SuperQ** [comment]
For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
