### ISSUE TITLE
Document topk function 

### ISSUE THREAD

**Issue by daixiang0** [prometheus/docs#1296]
In [example](https://prometheus.io/docs/prometheus/latest/querying/examples/), i see `topk`, but in [function](https://prometheus.io/docs/prometheus/latest/querying/functions/), i can not see any details.

If necessary, i would like to add this.

**Comment by brian-brazil** [comment]
It's an aggregator rather than a functino: https://prometheus.io/docs/prometheus/latest/querying/operators/#aggregation-operators
