### ISSUE TITLE
Promtool unit test rules support values as a range

### ISSUE THREAD

**Issue by bosschaert** [prometheus/docs#1305]
I am using the promtool unit testing support to test my alerts and recording rules.

One thing that would be great is if I could, instead of providing a specific expected value, I could give a range within which this value should be. For example I have this rule:

        - record: avg_read_latency_5m
          expr: histogram_quantile(0.999, rate(duration_bucket[5m]))

And then I have the following test

    evaluation_interval: 1m
    tests:
      # This test provides 5 durations of 1 second every 10 seconds. 
      - interval: 10s
        input_series:
        - series: 'duration_bucket{namespace="a",le="0.01"}'
          values: '0+0x120'
        - series: 'duration_bucket{namespace="a",le="0.1"}'
          values: '0+0x120'
        - series: 'duration_bucket{namespace="a",le="1.0"}'
          values: '100+5x120'
        - series: 'duration_bucket{namespace="a",le="+Inf"}'
          values: '100+5x120'
        promql_expr_test:
          - expr: avg_read_latency_5m
            eval_time: 10m
            exp_samples:
              - labels: 'avg_read_latency_5m{namespace="a"}'
                value: 0.9991

This above test passes, but all the inputs are at exactly 1 second. I guess the `0.9991` instead of `1.0` result is related to a slight mismatch at the boundaries at which the samples are taken? 
In that case it would be good to be able to, instead of using `0.9991` as expected value, be able to specify something like `1.0 ±3%` or something like this.

**Comment by brian-brazil** [comment]
PromQL is meant to be fully deterministic, so there's no need for that. There seems to be a bug here though, as this should be returning 1.

Can you file a bug in the prometheus repo?

**Comment by bosschaert** [comment]
Thanks @brian-brazil - I clearly posted this in the wrong repo...
