### ISSUE TITLE
Document /-/healthy and /-/ready

### ISSUE THREAD

**Issue by finkr** [prometheus/docs#1310]
The  `/-/healthy` and `/-/ready` endpoint where added in issue [#2831](https://github.com/prometheus/prometheus/issues/2831)

If it's implemented, it's worth being documented too :-)

## Liveness:
@beorn7 said:
> Prometheus should bind to `/-/healthy` immediately after startup and keep responding 200 for as long as it doesn't wish to get killed.

Note that the expected behavior is currently discussed in issue [#4624](https://github.com/prometheus/prometheus/issues/4624) that may need need to get that fixed before  (`/graph` returns 503 but `/-/healthy` returns 200 )

The behavior of those endpoints were further discussed in #3650.

## Readiness

@beorn7 said:
> Prometheus should start responding 200 to /-/ready once it is ready to accept queries.

@discordianfish said:
> `/-/ready` is suppose to respond with 200 no matter what. It can be used as liveness probe in kubernetes: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/

**Comment by brian-brazil** [comment]
Would you like to send a PR? The docs for this are over in the prometheus repo.

**Comment by finkr** [comment]
Any hint on where to document it ? API query ?

While https://github.com/prometheus/prometheus/issues/3650, I wonder what's the expected behavior for /-/healthy 

Is it correct to state and explain that /-/healthy and /-/ready are expected to be used and behave as explained in [Kubernetes doc]( https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/)

**Comment by brian-brazil** [comment]
I'm not sure to be honest. We might need a new page. /-/reload should also be covered.

I'd keep our docs standalone in this regard.

**Comment by beorn7** [comment]
I'm pretty sure that the `/-/healthy` endpoint should be used for the K8s liveness probe and the `/-/ready` endpoint for the K8s readiness probe. I think @discordianfish was wrong in the statement you quoted

**Comment by discordianfish** [comment]
Yes, I got this mixed up and @beorn7 is right:

- `/-/healthy` is suppose to always return 200 unless prometheus wants to get killed (which I don't think is ever the case.
- `/-/ready` is suppose to return 200 when prometheus is ready to respond to queries, e.g it shouldn't return 200 when starting it and during crash recovery etc
