### ISSUE TITLE
split the ever-growing misc exporters section

### ISSUE THREAD

**Issue by anarcat** [prometheus/docs#1320]
The misc section in the [list of exporters](https://prometheus.io/docs/instrumenting/exporters/) is getting out of control, with now 38 entries of various unrelated things mixed together.

Here are the item counts at the time of writing:

 * Databases: 22
 * Hardware: 12
 * Messaging: 10
 * Storage: 6
 * HTTP: 9
 * APIs: 14
 * Logging: 3
 * Other monitoring systems: 23
 * Miscellaneous: 38
 * Other software: 31
 * Third-party: 10

It's the largest section, and because there's so much stuff in there, there are a lot of hidden gems new users will miss. I totally missed and underestimated the importance of the blackbox exporter for example. In #1319, I suggested at least one group might be usefully split out of the miscellaneous section, but I'm not sure yet if I could come up with a good definition.

But somehow I feel those belong together:

## Network services

   * [BIND exporter](https://github.com/digitalocean/bind_exporter)
   * [Blackbox exporter](https://github.com/prometheus/blackbox_exporter) (**official**)
   * [Dovecot exporter](https://github.com/kumina/dovecot_exporter)
   * [Kannel exporter](https://github.com/apostvav/kannel_exporter)
   * [PowerDNS exporter](https://github.com/ledgr/powerdns_exporter)
   * [SABnzbd exporter](https://github.com/msroest/sabnzbd_exporter)
   * [Smokeping prober](https://github.com/SuperQ/smokeping_prober)
   * [SMTP/Maildir MDA blackbox prober](https://github.com/cherti/mailexporter)
   * [SoftEther exporter](https://github.com/dalance/softether_exporter)
   * [Unbound exporter](https://github.com/kumina/unbound_exporter)

I would possibly even include those in the list:

   * [rTorrent exporter](https://github.com/mdlayher/rtorrent_exporter)
   * [Transmission exporter](https://github.com/metalmatze/transmission-exporter)

We could also have a section on:

## Issue trackers and CI

   * [Bitbucket exporter](https://github.com/AndreyVMarkelov/prom-bitbucket-exporter)
   * [Confluence exporter](https://github.com/AndreyVMarkelov/prom-confluence-exporter)
   * [JIRA exporter](https://github.com/AndreyVMarkelov/jira-prometheus-exporter)
   * [Jenkins exporter](https://github.com/lovoo/jenkins_exporter)
   * [Bamboo exporter](https://github.com/AndreyVMarkelov/bamboo-prometheus-exporter)

And also:

## Load balancers

   * [ACT Fibernet Exporter](https://git.captnemo.in/nemo/prometheus-act-exporter)
   * [BIG-IP exporter](https://github.com/ExpressenAB/bigip_exporter)
   * [Kemp LoadBalancer exporter](https://github.com/giantswarm/prometheus-kemp-exporter)

There are also some items that seem to belong to existing sections:

## other monitoring

   * [Cachet exporter](https://github.com/ContaAzul/cachet_exporter)
   * [cAdvisor](https://github.com/google/cadvisor)
   * [Kibana Exporter](https://github.com/pjhampton/kibana-prometheus-exporter)
   * [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics)

## Databases

   * [Presto exporter](https://github.com/yahoojapan/presto_exporter)

Which would end up reducing the Miscellaneous section to those 13 entries:

## Miscellaneous

   * [BOSH exporter](https://github.com/cloudfoundry-community/bosh_exporter)
   * [ccache exporter](https://github.com/virtualtam/ccache_exporter)
   * [eBPF exporter](https://github.com/cloudflare/ebpf_exporter)
   * [Ethereum Client exporter](https://github.com/31z4/ethereum-prometheus-exporter)
   * [JMeter plugin](https://github.com/johrstrom/jmeter-prometheus-plugin)
   * [Meteor JS web framework exporter](https://atmospherejs.com/sevki/prometheus-exporter)
   * [Minecraft exporter module](https://github.com/Baughn/PrometheusIntegration)
   * [OpenStack exporter](https://github.com/Linaro/openstack-exporter)
   * [PHP-FPM exporter](https://github.com/bakins/php-fpm-exporter)
   * [Process exporter](https://github.com/ncabatoff/process-exporter)
   * [Script exporter](https://github.com/adhocteam/script_exporter)
   * [Shield exporter](https://github.com/cloudfoundry-community/shield_exporter)
   * [Xen exporter](https://github.com/lovoo/xenstats_exporter)

Do you see what I'm getting at here? The important part is not the exact list of what goes where, but to create a few more categories to reduce the size of the Misc section...

Alternatively, I wonder if it wouldn't be a good idea to consider creating a separate "marketplace" like [Nagios Exchange](https://exchange.nagios.org/), [Munin-contrib](https://github.com/munin-monitoring/contrib/) or [Monitoring-plugins](https://www.monitoring-plugins.org/) to move that list out of the documentation site and unleash the POWER of the MARKET. ;)

**Comment by brian-brazil** [comment]
Several of those don't look right, but the issue trackers one should work.

> Alternatively, I wonder if it wouldn't be a good idea to consider creating a separate "marketplace" like Nagios Exchange, Munin-contrib or Monitoring-plugins to move that list out of the documentation site and unleash the POWER of the MARKET. ;)

There's curation going on here, a ~full list of everything is on the wiki port list.

**Comment by anarcat** [comment]
oh i didn't notice the wiki...

so we should just duke out the details in a PR I guess?

**Comment by brian-brazil** [comment]
Presto and the issue trackers one can be done. The rest seem a bit tenuous/incorrect.

**Comment by anarcat** [comment]
> Presto and the issue trackers one can be done. The rest seem a bit tenuous/incorrect.

alright, I made #1323 for those, but I still think there's more sorting to do.

What about a load balancers section? Or moving cAdvisor and friends to "other monitoring"?

I also feel that stuff like the blackbox exporter, bind, dovecot and so on belong in a separate section than "misc"... Those are critical components that I suspect most people are looking for when they are looking at that page, compared to some less popular tools like (say) the minecraft exporter. ;)

**Comment by brian-brazil** [comment]
> Or moving cAdvisor and friends to "other monitoring"?

cAdvisor is not a monitoring system, it's basically just serving up data from /proc and /sys. By that definition the node exporter would also be other monitoring.

> Those are critical components that I suspect most people are looking for when they are looking at that page, compared to some less popular tools like

I'd expect users to be using the search function given the length of the page.

**Comment by anarcat** [comment]
> cAdvisor is not a monitoring system, it's basically just serving up data from /proc and /sys. By that definition the node exporter would also be other monitoring.

then maybe it belongs with "hardware" like node exporter? ;) how about kube-stat or kibana? aren't those monitoring systems as well?

> I'd expect users to be using the search function given the length of the page.

a table of contents would certainly help with that though. :)

**Comment by brian-brazil** [comment]
> kube-stat

Exporter for Kubernetes, nothing to do with hardware or monitoring.

> kibana

Those are metrics about kibana itself.

**Comment by anarcat** [comment]
*shrug* so I guess we're done here. i did try. :)
