### ISSUE TITLE
SSL and auth for Prometheus API

### ISSUE THREAD

**Issue by trevorwhitney** [prometheus/docs#1329]
Hey all! I know this has been discussed before, and was previously listed as a non goal in #149. However, I saw that it was discussed at the [Prometheus Dev Summit 2018](https://docs.google.com/document/d/1-C5PycocOZEVIPrmM1hn8fBelShqtqiAmFptoG4yK70/edit#heading=h.6owg7g3bt1pd), and it looked like it might be back on the table to at least allow the option of specifying client certs and doing mutual TLS for the API? Is my understanding around this correct, and is this indeed on the road map? If so, has any work been done for it yet? 

My team and I would be happy to contribute to this work. If there is not a plan already, our thoughts were that it could be off by default (backwards-compatibility), but if a server cert and key plus a CA were specified, the API would require valid client certs.

**Comment by brian-brazil** [comment]
You're looking for https://github.com/prometheus/node_exporter/pull/1277

**Comment by trevorwhitney** [comment]
@brian-brazil thanks so much, exactly what I was looking for. Closing.
