### ISSUE TITLE
Concern about "Writing exporters should retrieve metrics when Prometheus scrapes them" guidance

### ISSUE THREAD

**Issue by tomkerkhove** [prometheus/docs#1331]
As part of https://github.com/prometheus/docs/pull/1312 & https://github.com/tomkerkhove/promitor/issues/467, I'm checking to improve the way our Azure Monitor exporter works in order to make it compliant with the [guidance for writing exporters](https://prometheus.io/docs/instrumenting/writing_exporters/).

However, it mentions the following in ["Scheduling"](https://prometheus.io/docs/instrumenting/writing_exporters/#scheduling):
> Metrics should only be pulled from the application when Prometheus scrapes them, exporters should not perform scrapes based on their own timers. That is, all scrapes should be synchronous.

This guidance works fine if it's a sidecar for a container that is running inside the cluster and provides a handful of metrics.

## We have our concerns about the guidance for "proxy" exporters for external APIs, like Azure Monitor
However, in our scenario, we are exposing Azure Monitor metrics to Prometheus via our scraping endpoint which serve [the configured metrics by the consumer](https://promitor.io/configuration/metrics/).

This means that they can configure 1, 2, 10 metrics to scrape up to 20, 50, 100 of them. This means that the operation would become very chatty given the sheer amount of API calls we need to do in order to gather all the required information.

For this reason, we've initially implemented our own scheduling capability, configurable per metric, and provide a timestamp which reflects when it was last scraped.

## We're open for feedback
In our scenario, I think this is the best approach and am considering this to be the best viable approach for our scenario. However, since we want to be compliant I'd like to verify this with you and am open to discussing alternatives.

## Our main concerns
However, I have my concerns about moving to a "scrape when Prometheus wants us to" model for the following reasons:
1. This does not scale for a lot of metrics given we are an aggregate on top of an external service
   - Requests from Prometheus will time out, or only get a subset of all results in time
2. We support scraping in different frequencies which serve different use-cases. 
   - Moving away from this would mean deploying a lot of instances and scrape endpoints which increases overhead and resource consumption

**Comment by SuperQ** [comment]
There are several things you can do to mitigate this, without having to have in-exporter scheduling.

1. You can cache the API requests, with a TLL appropriate for the endpoint.
2. You can split the registries into different collectors.

For example you can register other URL paths for metrics that you need to scrape at a different frequency. For example, normal metrics that are fine to be scraped can be on `/metrics`. Things that you only want to scrape once per minute can be on `/slow_metrics`. Then the user can configure two different scrape jobs to gather the metrics at different intervals. This can also be done via URL parameters. For example, we do this in the node_exporter and the mysqld_exporter.

This solves the problems while staying within best practices.

**Comment by beorn7** [comment]
In case of slow data collection, I like the approach taken by https://github.com/soundcloud/collins_exporter . See explanation in the README.md. It doesn't need its own scheduling, but it will still avoid overlapping metrics collection.

**Comment by brian-brazil** [comment]
Over in the other Azure exporter, we've had no reports of this type of slowness so this is likely over-optimising in this case.

**Comment by tomkerkhove** [comment]
Thank you @beorn7 & @SuperQ for your insights. I'll think about it and maybe migrate to the recommended approach.
