### ISSUE TITLE
Outdated grafana version

### ISSUE THREAD

**Issue by kornerc** [prometheus/docs#1355]
In the docs describing the [grafana intregration](https://github.com/prometheus/docs/blob/master/content/docs/visualization/grafana.md), an old version of grafana is used (version 2.5.0).

I run into an error with the Prometheus server URL `http://localhost:9090/`.
Version 2.5.0 of grafana had problems with the slash at the end of the URL.
Removing the slash resovled the problem.

I also tried it with version 6.1.6, which dosen't throw errors with the URL `http://localhost:9090/`.

**Comment by SuperQ** [comment]
Yes, that's a very old example. I would probably just remove the copy-n-paste and only link to the official install docs.
