### ISSUE TITLE
"weight" and "grams" is not correct physics parlance or SI

### ISSUE THREAD

**Issue by janvanoort** [prometheus/docs#1400]
In https://github.com/prometheus/docs/blob/master/content/docs/practices/naming.md
"weight" should be "mass",  and the SI unit for it is kilogram, not gram.

**Comment by brian-brazil** [comment]
The base unit for mass in Prometheus terms is grams, we're trying to avoid millikilograms.

**Comment by janvanoort** [comment]
As you like it. "Millikilograms" would, of course, be ridiculous. Still, the SI unit for mass is the kilogram. Your choice if you want to be completely SI-compliant or not :-)

**Comment by beorn7** [comment]
I'd be very much for replacing "weight" with "mass". And a remark that we deliberately chose to use grams despite kilogram being the SI base unit cannot harm. We already have a "remark" column in the table. I'll send a PR.
