### ISSUE TITLE
Update Alerting rules Templating documentation

### ISSUE THREAD

**Issue by Sic4Parvis9Magna** [prometheus/docs#1409]
Hi all,
Recently I faced a tricky case while working with Prometheus, I was intended to use GO templates to provide more agility in alert configurations. 
[Documentation](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#templating) has a case in which it exposes syntax and provides users with an example of how to use such templates. But still, I cannot find an answer in the documentation on the following question: "If in **exp** section we use more than one metric, whose labels comes to a template?" 
`
- alert: tricky case
    expr:  metric_A{label_A="A"} == 0 and metric_B{label_B="B"} > 10
    for: 5m
    labels:
      severity: page
      lab_a: "{{ $labels.label_A }}"
      lab_b: "{{ $labels.label_B }}"
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
`
After a while, I found the answer using the PAT tool and a few tests.  There are points left:

- Is that case described in current documentation?
- If not, I would like to describe it on my own, but I cannot find an appropriate file in the master branch, where is [he](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#templating)?

**Comment by brian-brazil** [comment]
This is documented at https://prometheus.io/docs/prometheus/latest/querying/operators/#logical-set-binary-operators
