### ISSUE TITLE
Broken links in alerting overview doc file

### ISSUE THREAD

**Issue by nicocolt** [prometheus/docs#1472]
Hello,

On this file: [https://github.com/prometheus/docs/blob/master/content/docs/alerting/overview.md](https://github.com/prometheus/docs/blob/master/content/docs/alerting/overview.md) the 3 last links are all broken (404).

Best regards,
Nico

**Comment by brian-brazil** [comment]
All looks fine to me: https://prometheus.io/docs/alerting/overview/
