### ISSUE TITLE
typo in metric "http_requests_total" in documents

### ISSUE THREAD

**Issue by saranggithub** [prometheus/docs#1474]
In the document https://prometheus.io/docs/prometheus/latest/querying/examples/ please correct typo in metric "http_requests_total". It should be http_request_total

**Comment by brian-brazil** [comment]
Why do you think this is a typo?

**Comment by saranggithub** [comment]
should it be "request" ? I tried metric "http_requests_total" in
Prometheus and it did not work, however "http_request_total" worked.
Thats the reason, i felt extra "s" in requests is typo.

**Comment by brian-brazil** [comment]
That depends on what the Prometheus is scraping, and http_requests_total is the more typical name as it reads better grammatically.

**Comment by saranggithub** [comment]
Ok. For novice like me when I tried searching this metric it didn't work hence I raised it.
