### ISSUE TITLE
Add more examples to https://prometheus.io/docs/prometheus/latest/querying/examples/

### ISSUE THREAD

**Issue by HemantNegi** [prometheus/docs#1477]
I want to add more examples to https://prometheus.io/docs/prometheus/latest/querying/examples/ page but not able to find them in repo.

I have some examples of clamp_max(), max_over_time(), sum_over_time() functions.

Where can I add these in repo.

**Comment by brian-brazil** [comment]
It's at https://github.com/prometheus/prometheus/blob/master/docs/querying/examples.md

**Comment by HemantNegi** [comment]
Thanks for your help @brian-brazil 
I think this can be closed.
