### ISSUE TITLE
resolve_timeout documentation is outdated

### ISSUE THREAD

**Issue by Shadi** [prometheus/docs#1490]
From the documentation at alerting configuration [page](https://prometheus.io/docs/alerting/configuration/):
```
  # ResolveTimeout is the time after which an alert is declared resolved
  # if it has not been updated.
  [ resolve_timeout: <duration> | default = 5m ]
```

Looking at prometheus implementation, and this [comment]( https://github.com/prometheus/prometheus/pull/4538#discussion_r212914500)

it seems that this is not the case anymore.

**Comment by brian-brazil** [comment]
Would you like to send a PR indicating this is merely a default if the client doesn't send it?

Given the amount of confusion this particular setting hurts, it's likely worth moving it from the top and mentioning that this has no impact on Prometheus.

**Comment by Shadi** [comment]
Yes I will prepare a PR that will clear this up.

**Comment by Shadi** [comment]
Hi Brian, I created #1492, please let me know if you have any notes on the wording(English is not my first language)

**Comment by Shadi** [comment]
@stuartnelson3

**Comment by Shadi** [comment]
PR merged.
