### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by SilentImp** [prometheus/docs#1493]
https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#text-based-format

+ [client libraries](https://github.com/prometheus/docs/blob/master/docs/instrumenting/clientlibs)
+ [create your own](https://github.com/prometheus/docs/blob/master/docs/instrumenting/writing_clientlibs)

etc.

**Comment by brian-brazil** [comment]
That's the source code, it's fine on the website.

**Comment by beorn7** [comment]
"Website" as in https://prometheus.io/docs/instrumenting/exposition_formats/ .
