### ISSUE TITLE
Document Marathon SD

### ISSUE THREAD

**Issue by juliusv** [prometheus/docs#155]
See https://github.com/prometheus/prometheus/pull/902

**Comment by juliusv** [comment]
@xperimental would be up for the documentation PR for the Marathon SD? Otherwise I can try to give it a go. It'd be a blocker for the next release (not sure how far off, maybe a prerelease as early as next week).

**Comment by xperimental** [comment]
I planned to also do the documentation, but I am currently on vacation. I will be back on Monday...

**Comment by juliusv** [comment]
@xperimental No problem! Earliest we would do an RC would be later next week...

**Comment by brian-brazil** [comment]
This is done.
