### ISSUE TITLE
governance: Changing a vote

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/docs#1555]
Hi,

Our governance does not say what would happen if we change a vote.

Course of action:

A vote is called.

Person1: YES
Person2: YES
Person3: No because XXXX

Can Person1 and Person2 change their vote? Maybe Person3 has good arguments.

In which case, should there be a safety time frame after we  reach a majority, e.g 24h, to let people change their mind?

**Comment by beorn7** [comment]
That's a good point I was already thinking about.

My conclusion was, we should probably not overengineer and/or put all eventualities into the voting procedure. My rationale why the current state "just works":

- If a voting period opens, some discussion has already happened. If you are still not 100% sure what to vote, just don't cast your vote right ahead. You have the freedom to wait until the end of the voting period.
- If you nevertheless cast your vote and then get second thoughts, I'm sure nobody will object if you change your vote before the period ends. Sub-rationale for that: For one, it could be an actual mistake while sending the email ("I thought this was the other vote.", "I misread the item to vote about.", …) And second, even if the vote is over, and the vote was close enough that your decision would have mattered, you could just call for another vote, based on the fact that you have changed your mind. (Lazy consensus cannot be used to go against anything that was formally voted about, but a formal vote can change the outcome of a prior formal vote.)

**Comment by RichiH** [comment]
I also don't think we need to handle this case. Removals are safe-guarded, and the rest is done via social norms.
