### ISSUE TITLE
Visualization: Grafana Documentation Out-of-Date

### ISSUE THREAD

**Issue by HueGeneSymphony** [prometheus/docs#1568]
Following this documentation:
https://prometheus.io/docs/visualization/grafana/

The [configuring data source image](https://prometheus.io/assets/grafana_configuring_datasource.png) is out-of-date, and confusing given the [wording changes made to Direct / Proxy access](https://github.com/grafana/grafana/pull/11531).

Also, the documentation doesn't appear to be complete for a simple use case in docker.

Given
```
docker pull prom/prometheus
docker run -p 9090:9090 prom/prometheus
docker run -d --name=grafana -p 3000:3000 grafana/grafana
```
and using "Browser" access fails due to a CORS error I haven't quite figured out how to solve yet. Closest related issue is [this](https://github.com/grafana/grafana/issues/15225). The documentation should be updated with instructions for connecting when both prometheus and grafana are running as a docker container.

**Comment by kerneljack** [comment]
I have added a fix for this in [1609](https://github.com/prometheus/docs/pull/1609)

**Comment by kerneljack** [comment]
Can this issue be closed now @brian-brazil ?
