### ISSUE TITLE
metrics for prometheus.io itself

### ISSUE THREAD

**Issue by ryuheechul** [prometheus/docs#1573]
any plan to expose `https://prometheus.io/metrics` ?
today http://prometheus.io was quite slow and I thought it would be fun and nice that if this website dog-fooding prometheus and expose metrics so people can see (what's happening) and maybe learn from it as well.

**Comment by brian-brazil** [comment]
The website is served by 3rd parties, not by us running our own home-grown software, so such metrics simply aren't available to us. You can always look at the metrics of a Prometheus itself.

**Comment by ryuheechul** [comment]
I see thanks for the reply and understood. And I'm aware of prometheus exposing itself which is pretty cool.

**Comment by SuperQ** [comment]
The main host for the site is cloudflare, we could try out our new [cloudflare_exporter](https://gitlab.com/gitlab-org/cloudflare_exporter).

I was considering add this to the demo site metrics.
