### ISSUE TITLE
New database exporter

### ISSUE THREAD

**Issue by zrml** [prometheus/docs#1602]
Hi,
I would like to add InterSystems IRIS data platform to your list of exporters.
Effectively there is no exporter though, as we built it into it. :-)
Is that an issue for having a link and a mention in the exporters page?
Where could we send the link to? 
I would suggest the CE container on Docker HUB where we will have more information on it or perhaps the documentation page...

Let me know & Thank you

**Comment by brian-brazil** [comment]
You can send a PR if you'd like to ask for an exporter to be added.
