### ISSUE TITLE
Routing Tree Editor website not accurately simulating routes

### ISSUE THREAD

**Issue by briancaseyprovidertrust** [prometheus/docs#1638]
What happened:

I have been working on implementing the notifications in our prometheus install. I wanted to test the routes before I started blasting everyone with notifications so I went to the routing tree editor to test my config. I would apply labels and the alert never moved past the initial default receiver. I loaded my config into the website at https://prometheus.io/webtools/alerting/routing-tree-editor/

I suspected it was an error in my layout and spent time testing it and modifying it and nothing ever changed. To test my theory I used the following config file: "https://github.com/prometheus/alertmanager/blob/master/doc/examples/simple.yml"
In testing that file in the routing tree editor the same behaviour was observed. No matter what labels I used or modified the route never seemed to move beyond the default route.

What was expected:
I expected the route to follow and change receiver based on changed labels to test an alerting path.

**Comment by dayglojesus** [comment]
Confirmed. The routing tree is rendered accurately, but no matter what expression is placed in the "Match Label Set" field, the result is the same -- it only ever selects the `default` route.

Reproducible on Safari, Chrome and Firefox, no difference.

**Comment by brjlpz** [comment]
+1

**Comment by KR411-prog** [comment]
+1

**Comment by eugene-chernyshenko** [comment]
Still doesn't fixed

**Comment by juliusv** [comment]
Can confirm that this is still broken, so reopening.

To reproduce, just take the config from https://github.com/prometheus/alertmanager/blob/master/doc/examples/simple.yml and apply a match label set of `{service="database"}` or `{service="database",owner="team-Y"}`. They are both shown to go to the default receiver.

**Comment by Evreke** [comment]
After some investigation i think the problem is in massage function [here](https://github.com/prometheus/docs/blob/9ada72565ea35353843c591de3edc89917940c75/static/routing-tree.js#L148)

It tries to get undefined property named match for root object so the matchers array is always empty

**Comment by juliusv** [comment]
Nice, yeah that would be great! :)

**Comment by Evreke** [comment]
@juliusv I found working solution. Coding is done but I have to test all the cases and do some cleanup to be sure everything will work as intended. This week I will make a PR

**Comment by juliusv** [comment]
@Evreke Great! :)

**Comment by Evreke** [comment]
@juliusv Hi, Julius. I've done testing and found better solution using regexp that was kindly created by digitok from regex101.
PR is here #2065
