### ISSUE TITLE
TLS Encryption through nginx configuration issue

### ISSUE THREAD

**Issue by LukeWheeldon** [prometheus/docs#1650]
I have not been able to make the nginx setup work with the instructions provided on the following page: https://prometheus.io/docs/guides/tls-encryption/

In order to make it work I had to adjust two things from those instructions:
1. In the nginx.conf, instead of
        location /prometheus {
            proxy_pass http://localhost:9090/;
I have used
        location /prometheus {
            proxy_pass http://localhost:9090/prometheus;

2. I have not added the --web.route-prefix="/"

My system is Debian Buster, let me know if you need more details.

**Comment by brian-brazil** [comment]
It looks like the issue is the lack of a trailing slash on the location. Would you like to send a PR?

**Comment by LukeWheeldon** [comment]
oh wow I thought I had tried everything but apparently no.

thanks a lot @brian-brazil !

**Comment by brian-brazil** [comment]
We still have a minor doc bug that needs fixing.
