### ISSUE TITLE
Document clean shutdown beyond the FAQ

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/docs#167]
Currently we only mention in the FAQ that a clean requires sigterm or , that should be in the general docs too and also the http endpoint. 

Hmm, should we mention that in the crash recovery error message?

**Comment by hdost** [comment]
Perhaps it could go https://prometheus.io/docs/prometheus/latest/getting_started/  Add two more sections. "Reloading your configuration" and "Shutting down your instance"

**Comment by RichiH** [comment]
SGTM
