### ISSUE TITLE
Remove algolia temporary workaround

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/docs#1672]
https://github.com/prometheus/docs/blob/d4073d38baefbe1035ea72df3649cb37d3420854/layouts/footer.html#L27-L30

@juliusv Is it OK to remove this now?

**Comment by roidelapluie** [comment]
The issue is that alertmanager docs are not visible in algolia now.

**Comment by juliusv** [comment]
Turns out we also need to change our Algolia configuration to pick up the new meta tags. I submitted a PR for that:

https://github.com/algolia/docsearch-configs/pull/2045
