### ISSUE TITLE
Please add "A10" or "A10 Thunder" to the "Software exposing Prometheus metrics" list

### ISSUE THREAD

**Issue by jdallen-a10** [prometheus/docs#1704]
In Release 5.2 of our products, and going forward, our A10 Networks' Thunder solutions have built-in support for Prometheus metrics.  We also have a Prometheus-exporter for earlier versions of our software.

Let me know if you need any additional information or have questions.  John Allen, Sr. Solutions Engineer, A10 Networks (jallen@a10networks.com)

**Comment by jdallen-a10** [comment]
For Releases 5.1, 5.0, 4.1.4, & 4.1.1, here is the link to our Prometheus-exporter: https://github.com/a10networks/PrometheusExporter 
It would be great if we can also get a link to that in the 'Exporter' section as well.

Thanks!

**Comment by brian-brazil** [comment]
Do you want to send a PR mentioning the thunder in the software exposing list, lining to relevant docs?

**Comment by jdallen-a10** [comment]
Hi Brian!
PR as in a PR from Prometheus, or a PR from Us?  Either way, I would think so, but I'll let our Marketing dept. folks decide....just let me know what I need to do.

**Comment by brian-brazil** [comment]
Usually you'd send the PR, and then I can review.

**Comment by jdallen-a10** [comment]
So you would want to get a copy of the Press Release before we send it out for you to review?

**Comment by brian-brazil** [comment]
PR here is a Pull Request, see https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by jdallen-a10** [comment]
HA!  Ok....that's why I spelled it out, just in case ;). The web page at the bottom says to do either an issue or a PR to get added to the list, so that's why I did the issue. Might want to look into changing that if the process really is to open a PR. I'll close this and open a PR with the URLs for linking.  Thanks for straightening me out :)
