### ISSUE TITLE
Add "NDA" in the governance

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/docs#1817]
It might me great to state explicitly in the governance that team members can't share the discussions and the private docs outside of the team (even after they leave team).

Note that I do not really expect this to happen in practice.

**Comment by RichiH** [comment]
NDAs which span more than one jurisdiction are super hard to do right, and unless there's a signed contract, they will not hold up in court. In Germany, if your NDA prevents me from working, you have to compensate me or the NDA is void.

Long story short, I think outside of a trust-based system, we don't have anything, really.
