### ISSUE TITLE
Sometimes the recovery information of alterangerer (webhook) is not received

### ISSUE THREAD

**Issue by xiwangqi** [prometheus/docs#1825]
Sometimes the recovery information of alterangerer (webhook) is not received.

promethues (version 2.11.0)
altermanager(version 0.21.0)

promethues rules:
“””
·  - alert: ServiceQualityDecline
    expr: (min(collectd_link_e2e_score) by (hostname,env,bond,companyId,siteName,neId,deviceId,dstNe,companyName) - min(collectd_link_e2e_score{} offset 5m) by (hostname,env,bond,companyId,siteName,neId,deviceId,dstNe,companyName)) /min(collectd_link_e2e_score offset 5m) by (hostname,env,bond,companyId,siteName,neId,deviceId,dstNe,companyName) > 0.6
    for: 2m
    labels:
      severity: Emergency
    annotations:
      summary: "{{ $labels.neId }}: service quality has declined more than 60%."
      description: "{{ $labels.neId }}: E2E score of {{ $labels.link }} is `declined."
“””
altermanager config:
“””
global:
  resolve_timeout: 2m

templates:
- './sdwan.tmpl'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'aiwan_alert'
  routes:
    - match:
        env: st
      receiver: 'aiwan_alert'
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 24h
      continue: true
receivers:
- name: 'aiwan_alert'
  webhook_configs:
  - url: 'http://127.0.0.1:8001/api/v1/mgr/alerts'
    send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'Critical'
    target_match:
      severity: 'Warning'
    equal: ['alertname', 'env', 'instance']
“””

Most rules trigger alarms and alarm recovery are normal, but some alarms only receive the alarm message, and the recovery message is not received.
And make sure that the alarms on promethues and altermanager are restored. The webhook did not receive the recovery message from the altermanager.

Please help confirm whether this is a configuration problem or a bug. thank!

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
