### ISSUE TITLE
Prepare merging of https://github.com/yolossn/Prometheus-Basics

### ISSUE THREAD

**Issue by RichiH** [prometheus/docs#1856]
Let's talk about adapting https://github.com/yolossn/Prometheus-Basics a bit more to our structure so we can merge it over.

CC @roidelapluie @yolossn

**Comment by yolossn** [comment]
Shall I make the first draft and we can take it from there?

**Comment by yolossn** [comment]
Should this be a separate file under the introduction section or update the existing one?

**Comment by RichiH** [comment]
Sorry for going dark for so long. We have a docs working group in Prometheus now; #prometheus-docs-wg on CNCF Slack. Would you be interested in joining that?

**Comment by yolossn** [comment]
Thanks for letting me know I have joined the slack channel.

**Comment by mhausenblas** [comment]
@yolossn I very much like what you did there, lemme know if/how I can help please.

**Comment by yolossn** [comment]
@mhausenblas thanks, I wanted to know which parts should be added where, after the discussion in slack I have some clarity about the `introduction` and adding `Show me how it is done` to `first_steps`.  Do you see any other parts that can be added to the official documentation?  Also, do you want to take a shot at this?

**Comment by mhausenblas** [comment]
I'm happy to review your PR and once we've that in, I could take care of Alerting. WDYT?

**Comment by yolossn** [comment]
Yeah, works will raise a PR by the weekend

**Comment by hdost** [comment]
@RichiH could you link this to the docs-ng project?

**Comment by hdost** [comment]
@mhausenblas @yolossn Do we consider this finished now?

**Comment by yolossn** [comment]
@hdost The `alertmanager` tutorial is left.
