### ISSUE TITLE
Can federated prometheus hold data for longer time?

### ISSUE THREAD

**Issue by y509412** [prometheus/docs#1863]
I have 10 prometheus servers for 10 such environment, which has the metrics retention period of 14 days. I have one federated prometheus server which scrapes specific metrics from all the 10 prometheus servers. Can I accumulate/retain the data in federated prometheus for longer time, say 1 year? 

1) So that even if the local prometheus servers loose the metrics after 14 days, I will have those metrics in my federated prometheus. Is it possible?
2) One of the local prometheus servers has lost all the data. Will my federated prometheus have all those historical data?

**Comment by SuperQ** [comment]
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.
