### ISSUE TITLE
Getting started documentation needs update for New UI

### ISSUE THREAD

**Issue by robvanmaris** [prometheus/docs#1924]
The "Getting started" document (https://prometheus.io/docs/prometheus/latest/getting_started) refers to 

> the "Console" view within the "Graph" tab

However in the New UI (which is the default UI) the "Console" view is renamed to "Table".

**Comment by HelloKunal** [comment]
I guess the image at (https://prometheus.io/docs/guides/cadvisor/) also needs to updated since it shows "Console" view

**Comment by RichiH** [comment]
Closed via #1933
