### ISSUE TITLE
Dead link to grafana docs

### ISSUE THREAD

**Issue by blurks** [prometheus/docs#2017]
There is a dead link in the file ["Security Models" under section "API Security"](https://github.com/prometheus/docs/blob/master/content/docs/operating/security.md#api-security) to the grafana documentation on permissions.  

The [original link](http://docs.grafana.org/administration/permissions/#data-source-permissions) gives a 404.  I think, the new url might be [this](https://grafana.com/docs/grafana/latest/permissions/) but I am not sure.

**Comment by RichiH** [comment]
Thank you. https://web.archive.org/web/20200613071946/https://grafana.com/docs/grafana/latest/permissions/overview/ agrees with you. Do you want to send a PR?

**Comment by RiRa12621** [comment]
Took a stab at this https://github.com/prometheus/docs/pull/2058
