### ISSUE TITLE
Web site, FAQ: wrong URL

### ISSUE THREAD

**Issue by LupoOnGitHub** [prometheus/docs#2072]
Link [benchmark](https://github.com/prometheus/client_java/blob/master/benchmark/README.md) in https://prometheus.io/docs/introduction/faq/#what-is-the-performance-impact-of-instrumentation leads to 404, correct maybe is https://github.com/prometheus/client_java/blob/master/benchmarks/README.md

**Comment by hdost** [comment]
this should be fixed

**Comment by hdost** [comment]
@juliusv Could we close this?

**Comment by juliusv** [comment]
Yep, seems fixed, thanks! :)
