### ISSUE TITLE
documentation missing for ON() operator

### ISSUE THREAD

**Issue by fransf-wtax** [prometheus/docs#2106]
I've seen people use `ON()` in various Prometheus configurations I've looked at, and it is mentioned in [this blog post](https://www.robustperception.io/combining-alert-conditions). However, I don't see it documented anywhere in the [Querying documentation](https://prometheus.io/docs/prometheus/latest/querying/basics/). 

Would be helpful to have official documentation of this instead of having to go on what people on the internet happen to say about it.

**Comment by hdost** [comment]
So while it does appear in https://prometheus.io/docs/prometheus/latest/querying/operators/#vector-matching is there something further you think might be helpful?

**Comment by fransf-wtax** [comment]
OK, I must have completely overlooked that! :facepalm:

What might help is to add a bulleted list under the **Vector matching** section for the two matching "operators" just like there is a bulleted list of operators under **Arithmetic binary operators**, **Comparison binary operators**, etc. sections. That might make it easy to see when scrolling over the page. 

But otherwise, honestly don't know how I missed that.

Thanks!

**Comment by fransf-wtax** [comment]
Awesome @hdost , thanks for doing this! One sentence seems to have a typo or something, I added a comment on the pull request.
