### ISSUE TITLE
Clarify what "dimensions" are 🤔 

### ISSUE THREAD

**Issue by tredondo** [prometheus/docs#2114]
I'm coming from Influx and learning about Prometheus.

At https://prometheus.io/docs/practices/naming/, I see 

> A metric name should represent the same logical thing-being-measured across all label dimensions.

then later

> As a rule of thumb, either the `sum()` or the `avg()` over all dimensions of a given metric should be meaningful

I gather dimensions are points, i.e. float64 values? This is counter-intuitive, because when I think of "multiple dimensions", I think of separate concepts: height, width, length, weight etc. rather than values that change over time.

**Comment by RichiH** [comment]
It's usually better to open support requests under discussions. That being said:

The dimensions are labels and their values. Every label is a new, orthogonal dimension, their values are the position alongside said dimension.

**Comment by tredondo** [comment]
My request wasn't to clarify dimensions for me, but for new learners. Hence I think this clarification should be made in the documentation, rather than OOB in a support request.
