### ISSUE TITLE
Contradictive recommendations on naming for application-specific metrics

### ISSUE THREAD

**Issue by Alexsey** [prometheus/docs#2167]
According to the [dosc](https://prometheus.io/docs/practices/naming/#metric-and-label-naming), the naming of application-specific metrics should be
> A metric name... <...> ...should have a (single-word) application prefix relevant to the domain the metric belongs to. <...> For metrics specific to an application, the prefix is usually the application name itself.

But at the same time below we have
> Do not put the label names in the metric name, as this introduces redundancy and will cause confusion if the respective labels are aggregated away.

So does it mean that it's recommended to omit the label with the name of the application for application-specific metrics, or application-specific metrics is an exception and it's recommended to duplicate the application name in both metric and label?

After clarifying the ambiguity I'm willing to make a PR for the docs for clarifying the actual recommendation

**Comment by Alexsey** [comment]
@beorn7 thank you for the reply!

Could you please clarify
> If a metric is really application specific (e.g. prometheus_rule_evaluation_failures_total), then there is no need to duplicate the information

Do you mean that for application-specific metrics it's ok to put the application name as the prefix of the metric name, but in order not to duplicate the information we shouldn't add `job` label with application name?

**Comment by beorn7** [comment]
The `job` label is typically a target label added by Prometheus. And yes, Prometheus should still do that. (There is also no obligation to keep the job name the same as the general application name, or to use a job label at all. It really depends on your deployment model. But should both your job label and the metric prefix coincide, that's fine. Just don't add a label with the application name during instrumentation.)
