### ISSUE TITLE
Migrate to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by thisisobate** [prometheus/docs#2175]
Google is deprecating the Universal Analytics tag over Google Analytics 4. This effect will commence on July 1, 2023. You can learn more [here](https://blog.google/products/marketingplatform/analytics/prepare-for-future-with-google-analytics-4/)

This issue is part of a CNCF-wide effort to upgrade project websites to GA4 since Google has deprecated Universal Analytics (UA). For more details, see:

- https://github.com/cncf/techdocs/issues/108, including reference to:

   -  A suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

We should migrate the Prometheus website to GA4 as soon as possible so that by 2023Q3, when UA data collection stops, we will already have 1+ year of historical data.

Tasks, stage 1 (no code changes are necessary)

- [ ] Create a GA4 site tag using the GA4 setup assistant from the UA site tag console. This will create and [connect](https://support.google.com/analytics/answer/9973999) the two site tags.
- [ ] The new GA4 measurement ID is G-ADD_ID_HERE.
- [ ]  Confirm that the GA4 site tag is receiving events
- [ ] Confirm that the UA site tag(s) are still receiving events (with no code changes, there's no reason for it to not being receiving events, but it's good to check)

Tasks, stage 2 (optional, can be done later)

- Switch to using GA4 ID.
- Confirm that the GA4 site tag is receiving events
- Confirm that the UA site tag(s) are still receiving events

**Comment by thisisobate** [comment]
I'd be glad to create a new GA4 site tag under the GA CNCF-projects account if you'd like. We could then link the UA tags to the GA4 tag (and back).

**Comment by bwplotka** [comment]
Hey, thanks!

That would be helpful if you have time!

**Comment by RichiH** [comment]
CC @juliusv 
We were thinking about removing all tracking as we don't really leverage any of the data and as the easiest way to be compliant with GDPR is to not collect data in the first place.
That being said, if we don't switch it off, migration-as-a-service would be hugely appreciated.

**Comment by juliusv** [comment]
I'm fine with switching off the tracking! I think mainly the CNCF still wanted it though?

**Comment by thisisobate** [comment]
Yes. The foundation would need the data

**Comment by juliusv** [comment]
> I think the foundation would need the data

This sounds like a quote from a cyberpunk thriller TV show :)

Sounds good to me for now in any case if you want to change things over to the new GA and CNCF account.

**Comment by thisisobate** [comment]
Sure...happy to lead this effort @juliusv

**Comment by juliusv** [comment]
Sounds good to me. I think all current GA code on the site is just this, so it should be easy to replace: https://github.com/prometheus/docs/blob/918a96509582678fafb35f5dc9f35dcaea7591e4/layouts/footer.html#L9-L18

**Comment by chalin** [comment]
Hi all. I'm leading the GA4 migration effort for CNCF. FYI, I'll be taking over this effort from @thisisobate. Thanks @thisisobate for kicking things off!

I'm going to open another issue so that I have edit access.

**Comment by juliusv** [comment]
Closing as requested.
