### ISSUE TITLE
Permission to open a PR to fix a few typos

### ISSUE THREAD

**Issue by troyvit** [prometheus/docs#2241]
Hi -- I'm getting my feet wet contributing to open source projects. I noticed a minor typo on the docs pages and I'd like to make a PR to fix it. I just need permission to do so.

####The typo
There are a few places in the documentation where "setup" is used as a verb. In those cases it should be "set up". You can see an example [here](https://prometheus.io/docs/introduction/overview/). I made a fork in my [own repo](https://github.com/troyvit/prometheus-docs/tree/setup-to-set-up) and fixed the typos there if you would like to see it.

Thanks,

Troy

**Comment by RichiH** [comment]
Hi Troy; you don't need permission to open PRs, feel free to just do so :)
