### ISSUE TITLE
Docs: Getting Started: No "Tabular" view 

### ISSUE THREAD

**Issue by jeroentbt** [prometheus/docs#225]
Following http://prometheus.io/docs/introduction/getting_started/.
Under `## Using the expression browser` It says to navigate te the "Tabular" view under the "Graph" tab.
No such view is apparent.

![promtab](https://cloud.githubusercontent.com/assets/2703143/10305424/5229b592-6c20-11e5-89e7-00abbd0b5d22.png)
 
Running prometheus 0.15.1 via the latest prom/prometheus docker image (ecebe0acff82)

**Comment by juliusv** [comment]
Thanks, this was renamed a while ago in Prometheus, and the docs update was missed. Fix out in: https://github.com/prometheus/docs/pull/228
