### ISSUE TITLE
Node Exporter broken link

### ISSUE THREAD

**Issue by dpearceMN** [prometheus/docs#2253]
### What did you do?

https://prometheus.io/docs/guides/node-exporter/

In the first code block is this line:
`wget https://github.com/prometheus/node_exporter/releases/download/v*/node_exporter-*.*-amd64.tar.gz`

Which generates:

> 2022-12-25 04:57:23 ERROR 404: Not Found.

### What did you expect to see?

A download.

**Comment by LeviHarrison** [comment]
Hi there. I think it's implied that you're supposed to replace `*` with the version number you want to download.
