### ISSUE TITLE
Docs: Getting Started: GOPATH and mercurial

### ISSUE THREAD

**Issue by jeroentbt** [prometheus/docs#226]
Following the getting started tutorial, where one runs the example processes.
You could add people need to set up their `GOPATH` for `go get -d` and `go build` to work.

````
# Fetch the client library code and compile example.
git clone https://github.com/prometheus/client_golang.git
cd client_golang
export GOPATH=$(pwd)
cd examples/random
go get -d
go build
````

Also, when doing `go get -d` I got an error for Mercurial not being installed:

````
$ go get -d
go: missing Mercurial command. See https://golang.org/s/gogetcmd
package bitbucket.org/ww/goautoneg: exec: "hg": executable file not found in $PATH
````
Might be worth mentioning.

**Comment by juliusv** [comment]
Thanks, good point. I created https://github.com/prometheus/docs/pull/229 to address this.
