### ISSUE TITLE
Docs: Getting Started: Expression Browser

### ISSUE THREAD

**Issue by jeroentbt** [prometheus/docs#227]
>Go to the expression browser and verify that Prometheus now has information about time series that these example endpoints expose, such as the `rpc_durations_microseconds` metric.

If the "expression browser" is located under the "Graph" tab, adding the 3 random servers only provides 
- scrape_duration_seconds
- up

`rpc_durations_microseconds` is available on the respective metrics endpoints of the random services. It does not show up in the dropdown next to the blue "Execute" button.

**Comment by juliusv** [comment]
@jeroentbt Just testing this briefly (copying the config snippet from http://prometheus.io/docs/introduction/getting_started/#configuring-prometheus-to-monitor-the-sample-targets and starting up one example target), this seems to work for me.

Did you configure the Prometheus to scrape the example targets correctly? Do they show up as HEALTHY in the "Targets" list on http://localhost:9090/status?

**Comment by jeroentbt** [comment]
@juliusv They did not show up as healthy indeed. Docker issue where `localhost` for the targets is translated to the container hash.
The easiest fix was to target the `random` services at the external IP (internal range in this case) of the host on which I am running `prom/prometheus` and the 3 `random` servers.

Might be worth mentioning in the guide.

**Comment by juliusv** [comment]
Ok, the guide does everything without Docker though, so I would prefer to keep Docker-specific issues out of it. If someone goes off the path of the fixed instructions to do their own thing, they are kind of expected to be on their own, unless we also write a Docker-based tutorial.

**Comment by jeroentbt** [comment]
fair enough :)
