### ISSUE TITLE
Update docs for mongodb exporter link

### ISSUE THREAD

**Issue by stewartshea** [prometheus/docs#2294]
The mongodb exporter link refers to an outdated exporter (not updated since 2018), but there is an updated version in the prometheus-community org here: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-mongodb-exporter

**Comment by hdost** [comment]
@beorn7 I know there's something about listing multiple exporters. 
I feel like in this situation, it might be better to just add the one.
What do you think?
I'm a bit torn here because the existing one really isn't being updated. last release 2016...

**Comment by beorn7** [comment]
Is https://github.com/percona/mongodb_exporter a fork of the unmaintained one, or is it a completely new approach?

In the former case, I would just replace the old exporter with the new one. In the latter case, someone has to vet if there are use cases that the old exporter covers, but the new exporter doesn't. In which case we can list both, with a short comment when to use which. (At least that's how I understood the dev-summit consensus: "We will allow more than one exporter or integration to be listed for any particular thing if there is a good reason.")

**Comment by kevincantu** [comment]
Not certain how much history or compatibility they share, but the dcu one is really old.
