### ISSUE TITLE
For questions/help/support please use our [community](https://prometheus.io/community/) channels. There are more people available to potentially respond to your request and the whole community can benefit from the answers provided.

### ISSUE THREAD

**Issue by IIIdefconIII** [prometheus/docs#2410]
1. the issues still excist
2. this is no support at all
3. on the IRC channel nobody response
4. your closing the ticket just to get rid of it while the issue still excist
5. Not nice

https://github.com/prometheus/docs/issues/2409

**Comment by IIIdefconIII** [comment]
think i have said anough on the OP

**Comment by SuperQ** [comment]
This is not where support requests are answered. This is the documentation repo.

If you continue to open requests you will be banned.
