### ISSUE TITLE
Favicon is no longer being served.

### ISSUE THREAD

**Issue by grobie** [prometheus/docs#244]
```bash
curl -sSI http://prometheus.io/favicon.ico | grep HTTP
HTTP/1.1 404 Not Found
```

**Comment by juliusv** [comment]
There haven't been any recent changes to the favicon handling. The multitude of different favicons included in `<head>` for different devices/screen sizes seems to work at least for me on Chrome and Firefox. Is this Safari on Chrome not showing it or something?

**Comment by grobie** [comment]
Chromium on linux. It loads again today and my example above was under the assumption that there should be a file called favicon.ico.
