### ISSUE TITLE
Add a "popular" architecture entry on the downloads page, which includes arm64

### ISSUE THREAD

**Issue by gouthamve** [prometheus/docs#2542]
### Proposal

https://prometheus.io/download/ has darwin amd64, but not darwin arm64 (M1 Mac). I think nowadays, the latter is just as popular as the former and we should also include arm64 images.

**Comment by beorn7** [comment]
> I download the node_exporter-1.6.1.darwin-arm64 in my MacBook with M2 chip, but node_exporter throws exception when run node_exporter. same error with 1.7.0 version. which one should i download? Th

This would be a bug in node_exporter. If the problem persists, please file an issue in https://github.com/prometheus/node_exporter
