### ISSUE TITLE
Update comparison section

### ISSUE THREAD

**Issue by beorn7** [prometheus/docs#258]
From jaredwiltshire via prometheus-developers:

"The InfluxDB comparison highlights that Prometheus uses much less disk space than Prometheus due to its data storage model. However this seems to no longer be the case - https://influxdb.com/blog/2015/10/07/the_new_influxdb_storage_engine_a_time_structured_merge_tree.html
It also references a Github issue for InfluxDB regarding indexing which has since been closed."

I also believe we might want to include a few other monitoring and event-logging systems.

**Comment by brian-brazil** [comment]
We should mention things like Sysdig, Nagios and Zipkin.

**Comment by sdurrheimer** [comment]
And Bosun I guess.

**Comment by brian-brazil** [comment]
Expanded this a good bit recently.
