### ISSUE TITLE
Move Prometheus Client Data Exposition Format documentation

### ISSUE THREAD

**Issue by grobie** [prometheus/docs#28]
I might have missed it, but I couldn't find the client format documentation. The format is currently documented in a google doc, but I'd vote to move it here.

https://docs.google.com/document/d/1ZjyKiKxZV83VI9ZKAXRGKaUKK2BIWCT7oiGBKDBpjEY/edit

**Comment by juliusv** [comment]
It's linked off here: http://prometheus.io/docs/instrumenting/exposition_formats/

I'm open to moving the contents to the documentation directly. Though probably only the latest versions of the format.

**Comment by beorn7** [comment]
We also might want to finalize the formats at some point and call them v1.0.0.

**Comment by grobie** [comment]
Bump.

Having the format available in the docs makes it easier to link to them in discussions. This would be very helpful when proposing a native prometheus format stats exposition in open source code bases.

**Comment by juliusv** [comment]
I've started working on this, but it is a bit of a pain to transcribe to markdown. Markdown doesn't support tables without headers at the top (instead of at the left), and it also doesn't support lists in tables. I'm considering either using plain HTML for that or dropping the tables.

**Comment by juliusv** [comment]
I'm just doing nested lists for now, instead of tables.

**Comment by juliusv** [comment]
See https://github.com/prometheus/docs/pull/56
