### ISSUE TITLE
Document branches and publishing for the docs site properly.

### ISSUE THREAD

**Issue by beorn7** [prometheus/docs#292]
We need to clearly document at various places that prometheus.io is based on HEAD and represents the latest releases of the various other repos, while unreleased features (in the HEAD of the various repos) are in the `next-release` branch of docs.

Currently, we document something completely wrong on http://prometheus.io/docs/introduction/install/ :
"Note that this documentation (as published on prometheus.io) refers to the latest production release. The head of the prometheus/docs GitHub repository refers to the (possibly not yet released) head of the prometheus/prometheus (and other) repositories."

**Comment by fabxc** [comment]
The `next-release` branch is not sufficient. It provides no way for users
to access docs that are correct for the versions (Prometheus, Alertmanager,
...) they are running, which will become increasingly important in the
future.

**Comment by beorn7** [comment]
Post 1.0, we should definitely have "versioned" docs. Pre 1.0, I think the overhead is prohibitive.

**Comment by grobie** [comment]
The wrong documentation was removed in #405.
