### ISSUE TITLE
How does the grammar handle trailing comma?

### ISSUE THREAD

**Issue by grobie** [prometheus/docs#337]
I was just wondering how that's handled in alert definitions. A [google search](https://www.google.com/search?q=site%3Aprometheus.io&oq=site%3Aprometheus.io#q=site:prometheus.io%2Fdocs+trailing+comma) didn't reveal anything.

**Comment by brian-brazil** [comment]
The examples in https://prometheus.io/docs/alerting/rules/ have trailing commas. Is there something more you're looking for?

**Comment by grobie** [comment]
I guess just an explicit sentence somewhere on that page so that it can be googled.

**Comment by brian-brazil** [comment]
This is obsolete with the new yaml configs.
