### ISSUE TITLE
Document promdash label filters

### ISSUE THREAD

**Issue by grobie** [prometheus/docs#35]
I couldn't find the documentation about legend format filters. Maybe there are more promdash features which should be documented?

@stuartnelson3 @juliusv

**Comment by juliusv** [comment]
Yeah, from the bottom of http://prometheus.io/docs/visualization/promdash/:

----------
TODOs
===

Add documention about:

* annotation tags
* fullscreen / fullscreenTitle URL parameters
* document the dashboard JSON format

**Comment by juliusv** [comment]
@stuartnelson3 stu stu... @grobie really wants this :)

**Comment by sdurrheimer** [comment]
@grobie @juliusv I think this can be closed now :)
