### ISSUE TITLE
Document alertmanager notification template variables

### ISSUE THREAD

**Issue by juliusv** [prometheus/docs#359]
Besides http://prometheus.io/blog/2016/03/03/custom-alertmanager-templates/#comment-2586811288, we don't have any documentation on available Alertmanager notification template variables yet.

**Comment by mcrowson** [comment]
This lack of docs has made the learning curve for me super steep. The components all seem simple and straight forward, but not knowing how they all piece together has made this otherwise amazing piece of tech PITA to learn.
