### ISSUE TITLE
Document holt_winters function

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/docs#363]
https://github.com/prometheus/prometheus/pull/1485

**Comment by mdlayher** [comment]
Perhaps my search skills are just failing me, but do any of the functions provided by Prometheus currently have documentation?  If not, it would be nice to have documentation and examples for all of them.

**Comment by juliusv** [comment]
@mdlayher http://prometheus.io/docs/querying/functions/

**Comment by mdlayher** [comment]
@juliusv Thanks.  Wow.  My apologies. :)

**Comment by grobie** [comment]
@eliothedeman do you want to give this a try?

**Comment by eliothedeman** [comment]
Yeah I will take a shot at this tonight. Sorry about the delay.

**Comment by juliusv** [comment]
@eliothedeman 0.18.0 with this function is out now - any news here on the docs?
