### ISSUE TITLE
Missing cache buster

### ISSUE THREAD

**Issue by grobie** [prometheus/docs#369]
All assets should have a cache buster (using the current commit version), so that cloudflare won't deliver cached outdated asset versions.

**Comment by juliusv** [comment]
I'm on this...

**Comment by juliusv** [comment]
@ddfreyne While working on this, I ran into a nanoc problem: nanoc classifies all of our static CSS files (including https://github.com/prometheus/docs/blob/master/static/docs.css) as binary items, so trying to run a textual filter on them (to change any contained `url(...)` sections to cache-busted URLs) gives me an error:

```
Nanoc::Errors::CannotUseTextualFilter: The “Nanoc::Filters::CacheBuster” filter cannot be used to filter the “/assets/docs.css/” item (rep “default”), because textual filters cannot be used on binary items.
```

How does nanoc determine what is a binary item, and can I change it somehow?

**Comment by juliusv** [comment]
Discovered the reason. We're using the static datasource (https://github.com/prometheus/docs/blob/master/nanoc.yaml#L64-L66) to serve our static assets (CSS, JS, fonts, and images), and that automatically sets all managed files to binary: https://github.com/nanoc/nanoc/blob/3.7.3/lib/nanoc/data_sources/static.rb#L51

@ddfreyne any advice? I guess we should just not use the static datasource for items we want to filter textually? Another hacky workaround would be to exempt the jumbotron background image file from getting a cachebusting fingerprint, so we wouldn't even have to rewrite its URL in the CSS.
