### ISSUE TITLE
Create redirect pages

### ISSUE THREAD

**Issue by grobie** [prometheus/docs#391]
We do not serve pages for the main menu items. We should redirect to the first page of each section at least.

Github pages doesn't provide any HTTP server configuration, so we can't configure 30x HTTP responses. The options are either to use [HTML redirects](https://gist.github.com/maxim/1782458) or JS.

**Comment by brian-brazil** [comment]
Is this still relevant?

**Comment by grobie** [comment]
It's solved, mostly. `index.html` redirects don't seem to work correctly, will work on that.
