### ISSUE TITLE
Document federation use cases and examples

### ISSUE THREAD

**Issue by grobie** [prometheus/docs#394]
I was looking for some guidance around federation best practices, but couldn't find some immediately. It'd be great to add a section for that.

In our concrete case, we want to scrape some metrics from almost all our prometheus servers, so we list them all right now. The critical servers use a HA setup where we run two identical servers scraping the same targets. Our current federation config management configures them so that a service address is used, randomly pointing to one or the other node of a HA pair. This doesn't feel right to me.

@brian-brazil You mentioned some best practices here. Would it be better to always scrape all servers? What labeleling has emerged as best practice for this scenario?

**Comment by beorn7** [comment]
Which makes me think we might want to have access to all the SD mechanisms in federation, too. After all, if Prometheus monitors services managed by some kind of orchestration system, the odds are that the Prometheus servers are managed by the same system, and thus other Prometheus servers are discoverable via the same SD mechanism as targets.

**Comment by juliusv** [comment]
@beorn7 That's currently the case, no? Since federation targets are just normal targets with some extra settings.

**Comment by beorn7** [comment]
Yes, obviously. Pardon my stupidity.

So I guess the best way to federate from HA pairs is to scrape each of them but then also add labels so that they don't feed into the same series (because of `honor_labels`).

What do you (all) think?

**Comment by brian-brazil** [comment]
`external_labels` covers that use case already, you should probably only scrape one of them though.

**Comment by beorn7** [comment]
But how do you scrape the one that is up? Or in other words: I Want to scrape the same server of a pair normally, but if that one goes down, I want to fall back to the other...

**Comment by brian-brazil** [comment]
Global prometheus servers are inherently unreliable due to going over the WAN.

Attempting to work with two HA prometheus servers each with their own view of the world (which is only in theory identical) is going to involve substantial amounts of work for the user to try and eliminate all the potential weirdness. Better to keep it simple and accept a bit of availability loss for the brief time one a prometheus is down. The other prometheus in the pair will still be firing alerts, which is what is really important.

**Comment by beorn7** [comment]
Unless you have alerts for the global level...

Scraping both with some extra label seems to me the sanest thing.

**Comment by brian-brazil** [comment]
Alerts at a global level need to allow for additional races, so tend to have high thresholds to allow for this. As long as you get the server back up relatively quickly it'll likely be fine.

> Scraping both with some extra label seems to me the sanest thing.

That's what `external_labels` is for.

**Comment by beorn7** [comment]
So if you have global alerts, you needed to wake somebody up if the "wrong" server in a HA pair goes down. If you have many of those pairs, those incidents will happen relatively frequently. So I'd say that's a bad strategy for your alerting setup. It arguably defeats the purpose of an HA setup.

So I'd go for recommending federating from both servers with an extra label in the docs.

**Comment by brian-brazil** [comment]
> So I'd say that's a bad strategy for your alerting setup. It arguably defeats the purpose of an HA setup.

The purpose of a HA setup is that both send alerts if one fail, which it provides.

The purpose of a HA setup is not to provide a unified uninterrupted view of the services being monitored. This is fundamentally not possible.

> So if you have global alerts, you needed to wake somebody up if the "wrong" server in a HA pair goes down.

Global alerts are fundamentally unreliable. If it's that important an alert, it probably shouldn't be global.

**Comment by beorn7** [comment]
Symptom-based monitoring requires global alerts under circumstances. Let's say I want to get alerted if my global capacity reserve doesn't fulfill the "n+1" criterion anymore. In that case, I want to get woken up. I don't want to get woken up because somewhere in the world, one of my two local Prometheus servers is down.

**Comment by grobie** [comment]
Thanks, this looks like a lot of great material for a "best practices" section already. Right now, the federation servers I set up only scrape aggregation results which don't have instance labels, so I get the differentiation for free as new instance labels get attached.

It might be the responsibility of sd to deliver one healthy, ideally stable target.

**Comment by brian-brazil** [comment]
> It might be the responsibility of sd to deliver one healthy, ideally stable target.

That's not the role of SD, we want all targets so you can monitor them when they're not fully healthy.

**Comment by matthiasr** [comment]
What about a relabeling function that somehow allows to "pick one" (by a
specified label combination), and does so consistently between scrapes? like

```
- action: keep_one
  source_label: __address__
```

(slightly beyond the scope of documenting what is possible though)

**Comment by brian-brazil** [comment]
I don't think that belongs in SD, and that it would be greatly abused leading to both user problems and additional support load. Even for this use we'd have problems along those lines.

**Comment by brian-brazil** [comment]
http://www.robustperception.io/monitoring-without-consensus/ has some general background here, particularly the Perfection section.

**Comment by aecolley** [comment]
I was surprised that a timeseries federated from two replicated prometheus servers failed to merge into a single timeseries at the global level, and I found this thread which suggests that they shouldn't be allowed to merge. Why exactly is that a bad idea?

I understand that a point cannot be added to a timeseries if there's already a value with a newer timestamp, and that it would be very common for such out-of-order ingestions to be rejected. But for HA purposes, what's wrong with that? If I'm merging `dc:requests:rate5m` from two dc-level monitors with similar configurations, I'm happy to get stream 1, stream 2, or a merge of both streams; so long as the result has consistent labels. From the comments above, it appears that there is a firm design decision not to allow this. Why not?

Let's suppose that I'm resigned to having distinct timeseries for the HA pair. I could apply external labels such as `ha=left`, `ha=right`, but that presents obvious practical problems when querying for them. One way out is to introduce a new aggregation level below `dc:`, called `dcha:`. Each dc-level prometheus could calculate its `dcha:` variables and export them with `ha` external labels. Each global-level prometheus would combine them into a single `dc:` variable without the `ha` label. Apart from being ugly, this presents another problem: how do you express a query for `most_recent(dcha:requests:rate5m) without (ha)`? I could use `avg(...) without (ha)`, but that's extra nasty.

Also, how do I get rid of the `instance` labels that federation attaches to all variables? They don't belong there, and `relabel_config` doesn't want to remove them.

I'm trying to find a mechanism which will allow a single prometheus server to be taken out of service temporarily without needing a manual reconfiguration of the global prometheus. Is this a thing that federation permits?

**Comment by brian-brazil** [comment]
> Why exactly is that a bad idea?

You're presuming that the two Prometheus servers are seeing identical data and making identical calculations from that data.

> Each global-level prometheus would combine them into a single dc: variable without the ha label. 

This is the general approach to take if you want to do that, and the same used for any clustering-like system where not all targets necessarily agree on what the state of the world is (which is to say all clustering-like systems).

> From the comments above, it appears that there is a firm design decision not to allow this. Why not?

It's impossible for us to do this correctly. We take the approach of presenting the data as it is, and leaving it to the user to make whichever tradeoffs they want if they want to do a merge.

> Also, how do I get rid of the instance labels that federation attaches to all variables? 

`honor_labels: true`

> I'm trying to find a mechanism which will allow a single prometheus server to be taken out of service temporarily without needing a manual reconfiguration of the global prometheus. Is this a thing that federation permits?

Not per-se. You should try to ensure you gracefully handle any one Prometheus being down.

**Comment by brian-brazil** [comment]
https://prometheus.io/docs/operating/federation/ seems to cover this already.
