### ISSUE TITLE
digitalocean/rsyslog_exporter link is dead

### ISSUE THREAD

**Issue by sdurrheimer** [prometheus/docs#440]
https://github.com/prometheus/docs/blame/master/content/docs/instrumenting/exporters.md#L73

**Comment by grobie** [comment]
@taotetek do we need to remove that exporter or does it exist somewhere else now?

**Comment by grobie** [comment]
I reached out to DO per email. I guess we'll have to remove it, but let's wait 1-2 days in case they get back to us.
