### ISSUE TITLE
Clarify podspec requirements for Kubernetes pod/container discovery

### ISSUE THREAD

**Issue by matthiasr** [prometheus/docs#455]
As discussed in prometheus/prometheus#1693, the pod discovery requires named ports. This is kind of implied by

> For pods, the port is the "first port" for the first container reported by Kubernetes.

However I believe this is also incorrect since @pdbogen in the end changed prometheus/prometheus#1449 to look at [all containers](https://github.com/prometheus/prometheus/blob/e3ec8fa83bad9ebaaad608af10d7c9f1416332a6/retrieval/discovery/kubernetes/discovery.go#L934).

I'm not quite sure whether _naming_ the ports is actually required, or will this default to empty?

**Comment by pdbogen** [comment]
Named ports should not be required; I'll investigate and submit a patch if I find that's the case.

**Comment by pdbogen** [comment]
OK, bit of investigating done.

In #1693, the reporter was not exposing _any_ ports; currently a pod is only created as a target if _some_ port is found. It'd be relatively easy to change this (which would then allow that pod-target to be relabeled with a valid `__address__`). This probably best adheres to the network software principle; but it _might_ be acceptable (better, even?) to require users to adhere to a relatively easy best practice of explicitly exposing the metrics port from the container.

I'm happy to go with whatever the devs want on this one- the PR for documentation or for the code change ought to be straightforward.

**Comment by matthiasr** [comment]
I think requiring declared ports is reasonable. So the behaviour is that the _first_ port from _every_ container is used by default (and a port must be declared or the container is skipped), if it has a name it is added into the `__meta_kubernetes_pod_container_name` label for relabelling, and relabelling can modify the address based on annotations?

**Comment by brian-brazil** [comment]
We've other places (e.g. EC2) where there's no port provided and we use a default from the config. Is monitoring a pod without ports a sane thing to want to do?

**Comment by pdbogen** [comment]
The _numerically lowest_ port from the _alphebetically-by-name first container_ is used by default.

**Comment by matthiasr** [comment]
Kubernetes allows pods to just open any port they want, but to use them anywhere outside the pod declaring them is at least the normal thing to do. I would say we keep it like it is until someone has a concrete need where they can't declare any port.

**Comment by pdbogen** [comment]
So Kubernetes has this to say about the "ports" field on containers:
>  Exposing a port ... gives the system additional information about the network connections a container uses, but is primarily informational. Not specifying a port here DOES NOT prevent that port from being exposed. Any port which is listening on the default "0.0.0.0" address inside a container will be accessible from the network.

I don't think there's a right/wrong answer. I'd yell at (ahem, gently correct) an engineer in my organization that configured a container without any ports exposed but was expecting to use them anyway.

In some other Kubernetes situations, exposing ports _is_ required, e.g., if the pod is a service endpoint. I think this is a close-ish fit for that, so my _opinion_ is that the documentation should be updated to reflect that at least one port must be exposed on the container.
