### ISSUE TITLE
OFFSET documentation missing

### ISSUE THREAD

**Issue by fabxc** [prometheus/docs#50]
Title says it all. It should probably be added to the basics section.

**Comment by beorn7** [comment]
FTR: This is happening in https://github.com/prometheus/docs/pull/43

**Comment by fabxc** [comment]
Thanks, @bbrazil pointed me there as well and the issue is already closed.

**Comment by beorn7** [comment]
@fabxc I guessed that. My remark was targeted at others, so that they understand.
