### ISSUE TITLE
Several slack receiver parameters need some explanation

### ISSUE THREAD

**Issue by mpalmer** [prometheus/docs#501]
The Slack incoming webhook documentation linked to in the alertmanager configuration doesn't mention several of the parameters available in the `slack_configs` section:
- `color`
- `title`
- `title_link`
- `pretext`
- `fallback`

While `title` and `title_link` I can guess at (first line of text, emphasised, and associated link), the `color` parameter's defaults are non-obvious ("danger" and "good"...), and `pretext` and `fallback` I can only guess at.

**Comment by robcomcast** [comment]
I've been struggling to figure them out myself.
