### ISSUE TITLE
Add NATS exporter to list of 3rd party exporters

### ISSUE THREAD

**Issue by bjflanne** [prometheus/docs#523]
On this page (https://prometheus.io/docs/instrumenting/exporters/) can you add Lovoo's NATS exporter (https://github.com/lovoo/nats_exporter)? I see their Jenkins one already there, which is excellent, but I think many Prometheus users would also find the NATS one useful. Thanks!

**Comment by juliusv** [comment]
Sure! Do you want to do a PR against https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exporters.md?

**Comment by juliusv** [comment]
Ah, you already did. Thanks!

**Comment by bjflanne** [comment]
yes sir :) but no worries I did do the PR against wrong repo the first time around...now resolved ;)

**Comment by bjflanne** [comment]
We are nearly real-time here..not bad!
