### ISSUE TITLE
exposition format: Move protobuf format to proto3

### ISSUE THREAD

**Issue by beorn7** [prometheus/docs#549]
Since proto3 has no "unset" values anymore, we need to have all the values that may be "unset" (and where that has a meaning different from "default value") to be `repeated`, specifying that the value is repeated either zero times or once.

While doing so, we could also allow multiple samples in a single protobuf message (which must be timestamped then). This has to be added in the spec.

All these changes are backwards compatible with the proto2 protobufs.

See relevant discussion in https://github.com/prometheus/client_model/issues/13

**Comment by RichiH** [comment]
Just keep in mind that the text format should have the same capability.

**Comment by brian-brazil** [comment]
The text format already has this capacity.

**Comment by beorn7** [comment]
> > Just keep in mind that the text format should have the same capability.

> The text format already has this capacity.

What capability/capacity are you referring to? (And are you referring to the same one?)

**Comment by rektide** [comment]
> What capability/capacity are you referring to? (And are you referring to the same one?)

"The capability" seems to be,

> While doing so, we could also allow multiple samples in a single protobuf message (which must be timestamped then).

**Comment by beorn7** [comment]
Since our current use of protobuf for exposition is going away, and the new way that might come with OpenMetrics will be done from scratch, this issue is obsolete.
