### ISSUE TITLE
Getting started guide references incorrect metric

### ISSUE THREAD

**Issue by matthewcosgrove** [prometheus/docs#607]
The suggested metric seems incorrect and might be stale i.e. the expression browser does not return any data when following these instructions

> Go to the expression browser and verify that Prometheus now has information about time series that these example endpoints expose, such as the rpc_durations_seconds metric.

However, searching for 'rpc_durations_microseconds' does return data

**Comment by RichiH** [comment]
Are you running the current version? This was changed recently.

**Comment by matthewcosgrove** [comment]
This issue is in reference to the published docs https://prometheus.io/docs/introduction/getting_started/ which in turn references "git clone https://github.com/prometheus/client_golang.git"  

I assume they are out of sync in relation to using 'rpc_durations_microseconds' vs 'rpc_durations_seconds'

**Comment by RichiH** [comment]
Yep, that needs to be changed then. It's only seconds now, so the documentation is correct.
