### ISSUE TITLE
Environment variables for Azure secrets

### ISSUE THREAD

**Issue by gambrose** [prometheus/docs#608]
Looking at the Azure service discovery configuration it requires that we add client_secret in the config file I would rather not put this in as the config is visible in the web ui.

I see that the ec2 config can fall back to environment variables to pass access and secret keys. Is there equivalent vars for Azure plugin if not can they be added?

**Comment by brian-brazil** [comment]
The EC2 environment variable are there only because that's a native feature of the standard AWS libraries we use. Unless the Azure libraries offer this, it's not something we'd support.

**Comment by gambrose** [comment]
I have had a look at https://github.com/Azure/azure-sdk-for-go which is what I believe you are using. From what I see there is no built in support for environment variables.

The readme references AZURE_CLIENT_SECRET but it seams that this is just for use in the examples as it is explicitly implemented.

Is there a recommended way of storing secrets for Prometheus? As I want to avoid access to secrets from a public url.

**Comment by brian-brazil** [comment]
The config available over http will have all the secret fields masked, so you shouldn't need to do anything too special.

**Comment by gambrose** [comment]
Ah yes, I missed that. Thank.
