### ISSUE TITLE
List 3rd party software exporting prometheus metrics or supporting prometheus in other ways

### ISSUE THREAD

**Issue by beorn7** [prometheus/docs#68]
So far, we only list exporters, but there is so much more...

https://github.com/google/cadvisor
https://github.com/GoogleCloudPlatform/kubernetes
https://github.com/armon/go-metrics
https://github.com/coreos/etcd
https://github.com/mesosphere/kubernetes-mesos
https://github.com/peterbourgon/gokit

Anything else?

**Comment by fabxc** [comment]
The Django integration is interesting as well: https://github.com/korfuri/django-prometheus

**Comment by juliusv** [comment]
@brian-brazil @discordianfish

**Comment by beorn7** [comment]
https://github.com/google/mtail
https://github.com/Baughn/PrometheusIntegration

**Comment by oliver006** [comment]
https://github.com/oliver006/rethinkdb_exporter
https://github.com/oliver006/redis_exporter

**Comment by tgulacsi** [comment]
https://github.com/tgulacsi/prometheus_scollector

**Comment by fabxc** [comment]
https://github.com/dcu/mongodb_exporter

**Comment by juliusv** [comment]
This is awesome. I'm preparing a PR to put them under a "third party" section under http://prometheus.io/docs/instrumenting/exporters/. Some of them are clearly exporters in the sense that they extract metrics from an existing system and translate them into Prometheus metrics. Others are directly instrumenting the thing-to-be-measured, like Etcd. Others are kind of in-between, like cadvisor. It might be hard to draw clear limits here. How aobut just calling the section "Third-party integrations and exporters" (or similar) and mention them all in one go?

**Comment by juliusv** [comment]
I did end up splitting them up into exporters/directly-instrumented in the end.

Suggestion PR here: https://github.com/prometheus/docs/pull/71

**Comment by oliver006** [comment]
:+1:

**Comment by beorn7** [comment]
This has been fixed long ago.
