### ISSUE TITLE
Document that invalid label name chars get replaced by underscores in SD meta label names

### ISSUE THREAD

**Issue by juliusv** [prometheus/docs#735]
This is about SD meta labels like `__meta_kubernetes_node_label_<labelname>`.

https://prometheus.io/docs/operating/configuration does not mention that fact anywhere.

**Comment by infoverload** [comment]
Can I take this one?

**Comment by brian-brazil** [comment]
Go ahead.

**Comment by hdost** [comment]
@infoverload are you still interested in working on this?
