### ISSUE TITLE
Remove need to compile go from getting started section

### ISSUE THREAD

**Issue by grobie** [prometheus/docs#738]
The current getting started guide asks users to "Ensure you have the Go compiler installed and have a working Go build environment (with correct GOPATH) set up.". I believe this is an unnecessary requirement to get started with Prometheus and compiling golang a frequent source of user requests.

Either we provide binaries for the example targets, or we just use something more meaningful right away, like the node_exporter.

**Comment by RichiH** [comment]
Agreed.

Richard

Sent by mobile; excuse my brevity and the wall of text Gmail appends by
default.

**Comment by brian-brazil** [comment]
This hasn't been the case for a while.
