### ISSUE TITLE
Prometheus 2.0 docs needed

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/docs#740]
A bug to collect together all the big/small stuff we'll need to update in the docs for 2.0

**Comment by brian-brazil** [comment]
New `timestamp()` PromQL function

**Comment by brian-brazil** [comment]
New staleness handling

**Comment by brian-brazil** [comment]
New storage settings

**Comment by Gouthamve** [comment]
New rules and CLI flags.

Also, we need to figure out versioned docs.

**Comment by brian-brazil** [comment]
New admin/lifecycle flags, and also update security model.

**Comment by brian-brazil** [comment]
More of a changelog thing, but console template examples have been cut down.

**Comment by brian-brazil** [comment]
Removal of drop_common_labels, count_scalar and keep_common.

**Comment by nipuntalukdar** [comment]
What is the equivalent for keep_common in Prometheus 2.0+ ?

**Comment by brian-brazil** [comment]
> What is the equivalent for keep_common in Prometheus 2.0+ ?

Set the labels you want to keep in your `by` or exclude them in your `without`.

**Comment by brian-brazil** [comment]
I think it's just new storage and flags that need doing now, the rest are done or have PRs out.

**Comment by TimSimmons** [comment]
should the `v2/` or `v2/admin` api be documented?

**Comment by brian-brazil** [comment]
It should be

**Comment by AlekSi** [comment]
https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness is outdated

**Comment by brian-brazil** [comment]
The staleness docs are up to date.

**Comment by AlekSi** [comment]
> If no sample is found (by default) 5 minutes before a sampling timestamp, no value is returned for that time series at this point in time. This effectively means that time series "disappear" from graphs at times where their latest collected sample is older than 5 minutes or after they are marked stale.
> Staleness will not be marked for time series that have timestamps included in their scrapes. Only the 5 minute threshold will be applied in that case.

I'm pretty sure that part is not up to date. And @SuperQ agrees: https://groups.google.com/d/topic/prometheus-users/2DDL7FKMeVk/discussion

**Comment by brian-brazil** [comment]
That's up to date, it mentions being marked stale. See the previous paragraph also.

**Comment by SuperQ** [comment]
There are rules around staleness marking that seem to be missing from the documentation.

> If a target is removed, its previously returned time series will be marked as stale soon afterwards.

"soon" is not specific enough, it would be nice to have a paragraph that covers the information presented in [the PromCon talk](https://www.slideshare.net/brianbrazil/staleness-and-isolation-in-prometheus-20-promcon-2017).

**Comment by brian-brazil** [comment]
That's a pretty subtle implementation detail that I'd rather not get into in the docs, as it'd likely confuse more than explain.
