### ISSUE TITLE
Sample is not documented in glossary

### ISSUE THREAD

**Issue by bobrik** [prometheus/docs#750]
There are metrics like `scrape_samples_scraped`, but googling "prometheus samples" doesn't really explain what a sample is. There is a glossary:

* https://prometheus.io/docs/introduction/glossary/

But it doesn't explain samples either. There is also no explanation of timeseries, but that at least appears in overview:

* https://prometheus.io/docs/introduction/overview/

**Comment by lucperkins** [comment]
The more narrow issue of the glossary term has been addressed in #1082. In the coming weeks I'll be working to improve our story here more generally.
