### ISSUE TITLE
Document `relabel_configs` as a section

### ISSUE THREAD

**Issue by crccheck** [prometheus/docs#754]
Currently, the docs mention relabel config *entries*, https://prometheus.io/docs/operating/configuration/#%3Crelabel_config%3E but not that they can go into a section of the yaml called `relabel_configs`.

The docs have this structure:
* `relabel_config` -- a config entry
* `metric_relabel_configs` -- a yaml section section
* `alert_relabel_configs` -- a yaml section name

I think a new very slim section just like `metric_relabel_configs` and `alert_relabel_configs` would help a lot:
* `relabel_config` -- a config entry
* `relabel_configs` -- a yaml section section
* `metric_relabel_configs` -- a yaml section section
* `alert_relabel_configs` -- a yaml section name

**Comment by brian-brazil** [comment]
The docs already state this, I'd suggest looking more closely.

**Comment by crccheck** [comment]
> The docs already state this, I'd suggest looking more closely.

That's the problem, you have to look closely

**Comment by brian-brazil** [comment]
This is reference documentation, it's intended to be concise.

**Comment by crccheck** [comment]
At first, it seemed like the docs were inconsistent about what got to be a section and `relabel_configs` was missing, but after looking at other sections like `static_configs`, it looks like the docs are consistently inconsistent about what yaml sections are worth documenting.

Also, it turns out I needed `metric_relabel_configs`

**Comment by brian-brazil** [comment]
I've double checked all the relabel sections, this all looks to be consistent unless I missed something.
