### ISSUE TITLE
SSL Certificate for prometheus.io

### ISSUE THREAD

**Issue by pierzapin** [prometheus/docs#758]
Hi all.

As part of getting prometheus established as an approved monitoring and alerting solution here, our security guys have been reviewing the risk and compliance aspects.
They're largely ok with our intended use but one of their observed concerns with the prometheus.io site was : 

While the download site is using SSL and is overall graded 'A' by Qualys SSL Labs tool, the certificate used for the site can be used for many domains, including some that seem less than secure or even downright dodgy. See the list below of domains the SSL certificate can be used on (from the Alternate Subject Name extension on their cert). This means any of those sites may be able to spoof prometheus.io, using the same certificate.
sni194015.cloudflaressl.com,*.24srost.biz,*.bikelights.info,*.bosen.info,*.careerdev.info,*.cypera.com,*.doublo.info,*.fourthlinebobbles.com,*.gayfuckcam.com,
*.gold-38.biz,*.goldsilverreports.com,*.kiwhangkimtmaa.com,*.luxformat.tk,*.promcon.io,*.prometheus.io,*.qiwihb.xyz,*.ringever.tk,
*.screamingsquirrelshockey.com,*.silverspringmartialarts.com,*.ttdc.com.tr,*.ucsbrha.com,*.urypgdcafcymnt.ml,*.w24w.biz,*.yeswashington.tech,
*.zoloto25.biz,24srost.biz,bikelights.info,bosen.info,careerdev.info,cypera.com,doublo.info,fourthlinebobbles.com,gayfuckcam.com,
gold-38.biz,goldsilverreports.com,kiwhangkimtmaa.com,luxformat.tk,promcon.io,prometheus.io,qiwihb.xyz,
ringever.tk,screamingsquirrelshockey.com,silverspringmartialarts.com,ttdc.com.tr,ucsbrha.com,urypgdcafcymnt.ml,w24w.biz,yeswashington.tech,zoloto25.biz.

Any thoughts about swapping out to a cert that is a little more scoped to yourselves?

**Comment by brian-brazil** [comment]
We're hosting on github via cloudflare. We've no particular plans to move, as if either of those two companies has issues the entire internet has bigger problems.

**Comment by juliusv** [comment]
We are currently on Cloudflare's free (shared) SSL certificate plan. We could get a dedicated cert from them for $5 a month. Maybe worth thinking about?

**Comment by brian-brazil** [comment]
I don't see much benefit there, it'd still be using cloudflare so the threat model doesn't really change.

**Comment by juliusv** [comment]
Yeah, was just thinking that too. From a security point of view, it doesn't change much AFAICS. Only from a (potentially non-sensical) bureaucratic compliance aspect.

**Comment by pierzapin** [comment]
Thanks for the quick reply ;-) . Appreciated

**Comment by vonUtrecht** [comment]
The way I see it, any domain listed on the Subject Alt Name (SAN) extension on Prometheus.io site could - if they so desired - spoof Prometheus.io. Sure, most of your stuff is hosted in Github, so people _could_ go directly to the Github site, if they're aware of this issue. However, it still leaves any visitor to Prometheus.io open to potential spoofing. They could then click on any link - including "download" and find themselves infected with malware.
So, it does change the threat model quite a bit if you have your own scoped certificate.

**Comment by brian-brazil** [comment]
> The way I see it, any domain listed on the Subject Alt Name (SAN) extension on Prometheus.io site could - if they so desired - spoof Prometheus.io

No they couldn't, they'd have to find a severe vulnerability in Cloudflare to do so.
