### ISSUE TITLE
versioned docs

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/docs#769]
With the 2.0 alpha --> beta --> stable journey going to take several months, we should have separate docs for 2.x and 1.x.

This should also be the right opportunity to get versioned docs in place.

**Comment by grobie** [comment]
@Gouthamve and I just hopped on a call and discussed a rough outline of things to do:

* Move documentation
  * Best spot is likely each repository (prometheus docs move to prometheus/prometheus, alertmanager to prometheus/alertmanager, etc.). Has the nice side effect that people can read the docs locally, but will increase the amount of PRs and issues.
  * Use release branches like release-1.7 release-2.0 for versioned docs
  * Identify which parts are gonna stay in prometheus/docs (like glossary, faq, etc.) and which are specific docs for each project
* Implementation
  * Maintain a list of all repos and branches we want to create docs for in prometheus/docs
  * check them out before compiling pages (probably with make, look into git sparse checkout to reduce amount of files to copy)
  * Write a nanoc filter/helper to change all links to have the right prefix
  * add dropdown or something to select the base version
* Open/next questions
  * how to handle redirects
    * GH only supports html `<meta>` redirects, maybe enough if google supports it
    * other option is to host the page on digital ocean (because of cloud flare not a huge issue??)
  * nanoc 4 upgrade should come eventually, but is orthogonal
  * other optimizations to speed up the build process

**Comment by brian-brazil** [comment]
Would the plan be to keep everything serving off prometheus.io?

There's something to be said for having the header and css on everything, rather than the standard github interfance.

**Comment by grobie** [comment]
Oh yes, totally, sorry if that was unclear. Everything will still be on prometheus.io, we just move the documentation in each repo and clone them during the docs build process. The directory structure right before calling `nanoc build` would be something like

```
content/
  docs/
    prometheus/
      1.7/ # cloned from prometheus/prometheus branch: release-1.7 directory: docs/
      2.0/ # cloned from prometheus/prometheus branch: release-2.0 directory: docs/
      2.1/ # cloned from prometheus/prometheus branch: release-2.1 directory: docs/
    alertmanager/
      0.8/ # cloned from prometheus/alertmanager branch: release-0.8 directory: docs/
      0.9/ # cloned from prometheus/alertmanager branch: release-0.9 directory: docs/
```

During the nanoc build process, we'll need to update the links with a nanoc/ruby filter.

**Comment by brian-brazil** [comment]
That all sounds good to me.

As most repos don't use branches for releases, we should probably work off tags instead.

**Comment by grobie** [comment]
This was my first idea as well, but it would mean we could never fix/edit documentation once released, so actually it should be branches and not tags.

We'll start with prometheus and alertmanager, so we can postpone this discussion for now as both use release branches. From a prometheus/docs implementation, it doesn't matter whether the identifier is a git sha1, tag or branch name anyway, so it's something we can change on a per project basis.

**Comment by grobie** [comment]
See #851
