### ISSUE TITLE
Broken Links (404) 

### ISSUE THREAD

**Issue by socomsystems** [prometheus/docs#788]
https://github.com/prometheus/docs/blob/master/content/docs/querying/basics.md

404s for links provided in sections below.

**Comment by brian-brazil** [comment]
I can't see anything broken on https://prometheus.io/docs/querying/basics/, which link is the issue?

**Comment by socomsystems** [comment]
Links residing in the Operators and Functions paragraphs near the bottom.

**Comment by brian-brazil** [comment]
Those work fine for me. Note that the docs are meant to be used from the website, not the raw files in git.

**Comment by juliusv** [comment]
Yes, please see the final resulting site here, where all links are working: https://prometheus.io/docs/querying/basics/

Closing.
