### ISSUE TITLE
Link to Robin Greenwood on community.html leads to broken website

### ISSUE THREAD

**Issue by ahus1** [prometheus/docs#794]
On https://prometheus.io/community/ the link to Robin Greenwood, the contributor of the logo, leads to a (broken?) website. According to whois the domain is still registered to Robin Greenwood.

Suggestion: remove the link?

Other ideas?

**Comment by brian-brazil** [comment]
@juliusv Do you have updated details for Robin?

**Comment by juliusv** [comment]
Asking him...
