### ISSUE TITLE
Set html page title

### ISSUE THREAD

**Issue by grobie** [prometheus/docs#80]
The HTML page title currently always says "Prometheus". This isn't helpful for SEO and search reasons. Add the title of each page to the html title attribute, something like `$page | Prometheus` e.g. `Getting started | Prometheus`.

**Comment by juliusv** [comment]
This should be fixed by https://github.com/prometheus/docs/pull/83 (will be rolled out to prometheus.io in the next days - we currently don't roll out master to prometheus.io because we accidentally already merged the 0.14 docs stuff into it).

**Comment by fabxc** [comment]
Didn't we say docs/master should match prometheus/master? Which it does
again by now - so we'd need a stable tag to which we backport fixes that
apply to the current release.
