### ISSUE TITLE
Document the label_join() function

### ISSUE THREAD

**Issue by brian-brazil** [prometheus/docs#800]

**Comment by albertvaka** [comment]
For future reference, this was implemented here: https://github.com/prometheus/prometheus/pull/1147

**Comment by sipian** [comment]
I think this issue can be closed now since the documentation of label_join is in place.

**Comment by albertvaka** [comment]
Is it? It's not here: https://prometheus.io/docs/querying/functions/

**Comment by albertvaka** [comment]
Oh, I see the merge pull request though, I guess it will have to wait until the website is updated :)
