### ISSUE TITLE
Alertmanager HA configuration

### ISSUE THREAD

**Issue by josedonizetti** [prometheus/docs#844]
#Although I could find tutorials online like this robustperception blog https://www.robustperception.io/high-availability-prometheus-alerting-and-notification/, 
there's no documentation on the main prometheus website.

**Comment by josedonizetti** [comment]
Does it make sense? I'm up to write it.

**Comment by brian-brazil** [comment]
We don't really have a way to do howto/guides yet on prometheus.io, Right now https://github.com/prometheus/alertmanager#high-availability are the docs. A reference section could be added that duplicates the flag information.

**Comment by josedonizetti** [comment]
@brian-brazil Wasn't thinking about a howto. I haven't found any mention of alertmanager HA on prometheus.io. A newcomer opening the website after a google search would not know of such support unless he goes to the github repo. 

Maybe we could add a High Availability section at https://prometheus.io/docs/alerting/alertmanager just to state that the support exists, and link to github for more information on how to use.

What do you think?

**Comment by brian-brazil** [comment]
A brief section there would make sense.

**Comment by josedonizetti** [comment]
@brian-brazil Let me know if you anything else should be changed. Thanks.

**Comment by wfernandes** [comment]
Is AlertManager High Availability still under active development?
