### ISSUE TITLE
Implement relative name for versioned documentations

### ISSUE THREAD

**Issue by grobie** [prometheus/docs#854]
As a user,
in order to easily access the latest documentation page,
I need a relative name instead of a fixed version number.

@brancz proposed  the usage of a `latest` relative name. That's what CoreOS uses in [their docs](https://coreos.com/tectonic/docs/latest).

Open question:

* Do we want to use `latest` or rather `stable` so that these links don't include pre-releases?

**Comment by brancz** [comment]
I feel latest is commonly used to refer to the latest stable release, but have no objections to either naming. If we want to be extra detailed, maybe `latest-stable`.

**Comment by grobie** [comment]
As it seems our `latest` Docker tag also points to the last stable release, it probably makes sense to use that.
