### ISSUE TITLE
Promtool documentation should mention version

### ISSUE THREAD

**Issue by jsha** [prometheus/docs#890]
The instructions for promtool at https://github.com/prometheus/docs/blob/master/content/docs/querying/rules.md#syntax-checking-rules say:

```
go get github.com/prometheus/prometheus/cmd/promtool
promtool check-rules /path/to/example.rules
```

However, this will fail, because promtool has been updated to expect "check rules" (note the space). More importantly, the latest version of promtool expects version 2 format alert rules, and most existing configs use version 1 alert rules.

The promtool instructions should be updated to indicate how to check out an earlier version of the tool that will understand version 1 alert rules.

**Comment by grobie** [comment]
Has been fixed. We provide versioned documentation now. See https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/

**Comment by Jared-Janrain** [comment]
While you can switch between versions, there aren't any instructions on how to install the previous version.  When it stays to run `go get github.com/prometheus/prometheus/cmd/promtool`, that will go get the latest version which isn't compatible with 1.8

**Comment by mateng0915** [comment]
the execute command maybe wrong, my go version is 1.10.3, and after go get promtool, then run command is ./promtool check rules example_rule.yml
