### ISSUE TITLE
Add JIRA exporter to exporter section

### ISSUE THREAD

**Issue by AndreyVMarkelov** [prometheus/docs#896]
Add https://marketplace.atlassian.com/plugins/ru.andreymarkelov.atlas.plugins.prom-jira-exporter/server/overview to exporters section

**Comment by brian-brazil** [comment]
Would you like to send a pull request?

**Comment by AndreyVMarkelov** [comment]
Hello Brian. I have done: https://github.com/prometheus/docs/pull/897
