### ISSUE TITLE
https://prometheus.io/docs/concepts/metric_types/ returns 404

### ISSUE THREAD

**Issue by danhawkes** [prometheus/docs#913]
Not sure what's changed in the repo, as the markdown source still seems to be in [`docs/concepts`](https://github.com/prometheus/docs/tree/af71ef0da1d7837a6194f7d349c30a94d1394346/content/docs/concepts), and the pages either side of it seem to work.

**Comment by grobie** [comment]
@danhawkes Thanks for the report. We seem to have issues with the CDNs in front of the page. Can you check if it's still an issue for you, and if so, whether https://prometheus-docs.netlify.com/docs/concepts/metric_types/  results in a 404 as well?

**Comment by grobie** [comment]
We're suffering from an outage of our docs hoster http://netlifystatus.com/.

**Comment by danhawkes** [comment]
Both urls seem to work now, thanks.
