### ISSUE TITLE
Document that Prometheus 2.0 no longer supports the protobuf exposition format

### ISSUE THREAD

**Issue by cite-reader** [prometheus/docs#927]
The documentation page on exposition formats states:

>A server will prefer receiving the protocol-buffer format, and will fall back to the text-based format if the client does not support the former.

As of Prometheus 2.0.0, this is not true. It doesn't seem to support the protobuf format at all.

That section of prose should be updated to reflect that fact, and the **Supported in** secton of the comparison table should reflect the upper version bound, at a minimum. More generally this page could probably stand to be rewritten to reflect conclusions from, for instance, [this discussion.](https://github.com/RichiH/OpenMetrics/blob/master/protobuf_vs_text.md)

**Comment by juliusv** [comment]
While the table on https://prometheus.io/docs/instrumenting/exposition_formats/ lists the protobuf version as supported only in ">=0.4.0, <2.0.0", that could indeed be made clearer throughout the doc, especially now that most people should be on Prometheus 2.0.

**Comment by lucperkins** [comment]
@cite-reader @juliusv I'm happy to handle this. Feel free to assign me.

**Comment by RichiH** [comment]
@lucperkins I sent you a request to join this repo; you can then take issues yourself. As always, all commits must go through a PR.

**Comment by juliusv** [comment]
Yup, GitHub currently does not let me assign you, you'll have to join the repo :)

**Comment by brian-brazil** [comment]
There's no reference in the migration doc.

**Comment by rektide** [comment]
The original ticket linked a url, https://github.com/RichiH/OpenMetrics/blob/master/protobuf_vs_text.md , on protobuf vs text. That link is now 404.

Is there any documentation anywhere on the deprecation of protobufs? Any kind of migration announcement? I'm trying to find something to mention about this change, but I can't find any discussion on the web I can use to cite this event in Prometheus's life (other than this ticket, which doesn't discuss why this was done, or what happened, only mentions the ask for such a note).

**Comment by juliusv** [comment]
@rektide the doc that's missing seems to live here now: https://github.com/RichiH/OpenMetrics/blob/master/markdown/protobuf_vs_text.md

Permalink: https://github.com/RichiH/OpenMetrics/blob/bae0f117077294c57c0b115887495383730912df/markdown/protobuf_vs_text.md
