### ISSUE TITLE
kafka Monitoring with prometheus , grafana-dashboard

### ISSUE THREAD

**Issue by lordcf** [prometheus/docs#994]
Hello Team, 

we are trying to capture monitoring metrics of kafka into prometheus along with kafka based grafana dashboard- "https://grafana.com/dashboards/721"

step1 : configured kafka with prometheus following : Monitoring Kafka with Prometheus
 https://www.robustperception.io/monitoring-kafka-with-prometheus/

step2: Setting up Grafana for Prometheus
https://www.robustperception.io/setting-up-grafana-for-prometheus/

step 3: From this link, https://grafana.com/dashboards/721 we downloaded JSON file and imported to grafana for dashboard.  [reference - http://docs.grafana.org/reference/export_import/]

while starting kafka we have changed the port to 9090 instead of 7071.
accordingly we updated into the json file [7071-> 9090]

we are getting metrics data from step 1.
![image](https://user-images.githubusercontent.com/25821409/37914486-f16ab6f2-3134-11e8-8b67-912f38bdb5a7.png)

we are still facing issue of "No datapoints-No datapoints returned from metric query"
![image](https://user-images.githubusercontent.com/25821409/37914084-03f3d4e4-3134-11e8-9e22-df1a5a1d223e.png)

Any inputs or configuration missing or not in place ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
